// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/plugin/v3/admission.proto

package pluginv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation is the type of resource operation being checked for admission
// control.
// https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/apis/admission/types.go#L158
type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_CREATE      Operation = 1
	Operation_OPERATION_UPDATE      Operation = 2
	Operation_OPERATION_DELETE      Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_UPDATE",
		3: "OPERATION_DELETE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_CREATE":      1,
		"OPERATION_UPDATE":      2,
		"OPERATION_DELETE":      3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_grafana_plugin_v3_admission_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_grafana_plugin_v3_admission_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// GroupVersionKind identifies the properties of an object.
type GroupVersionKind struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Group       *string                `protobuf:"bytes,1,opt,name=group"`
	xxx_hidden_Version     *string                `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Kind        *string                `protobuf:"bytes,3,opt,name=kind"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GroupVersionKind) Reset() {
	*x = GroupVersionKind{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupVersionKind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVersionKind) ProtoMessage() {}

func (x *GroupVersionKind) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupVersionKind) GetGroup() string {
	if x != nil {
		if x.xxx_hidden_Group != nil {
			return *x.xxx_hidden_Group
		}
		return ""
	}
	return ""
}

func (x *GroupVersionKind) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *GroupVersionKind) GetKind() string {
	if x != nil {
		if x.xxx_hidden_Kind != nil {
			return *x.xxx_hidden_Kind
		}
		return ""
	}
	return ""
}

func (x *GroupVersionKind) SetGroup(v string) {
	x.xxx_hidden_Group = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *GroupVersionKind) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *GroupVersionKind) SetKind(v string) {
	x.xxx_hidden_Kind = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GroupVersionKind) HasGroup() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GroupVersionKind) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GroupVersionKind) HasKind() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GroupVersionKind) ClearGroup() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Group = nil
}

func (x *GroupVersionKind) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *GroupVersionKind) ClearKind() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Kind = nil
}

type GroupVersionKind_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Group   *string
	Version *string
	Kind    *string
}

func (b0 GroupVersionKind_builder) Build() *GroupVersionKind {
	m0 := &GroupVersionKind{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Group != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Group = b.Group
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Version = b.Version
	}
	if b.Kind != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Kind = b.Kind
	}
	return m0
}

// ValidateAdmissionRequest contains information from a Kubernetes admission
// request and the decoded object(s).
type ValidateAdmissionRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Operation      Operation              `protobuf:"varint,1,opt,name=operation,enum=grafana.plugin.v3.Operation"`
	xxx_hidden_Kind           *GroupVersionKind      `protobuf:"bytes,2,opt,name=kind"`
	xxx_hidden_ObjectBytes    []byte                 `protobuf:"bytes,3,opt,name=object_bytes,json=objectBytes"`
	xxx_hidden_OldObjectBytes []byte                 `protobuf:"bytes,4,opt,name=old_object_bytes,json=oldObjectBytes"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ValidateAdmissionRequest) Reset() {
	*x = ValidateAdmissionRequest{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAdmissionRequest) ProtoMessage() {}

func (x *ValidateAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateAdmissionRequest) GetOperation() Operation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Operation
		}
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *ValidateAdmissionRequest) GetKind() *GroupVersionKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return nil
}

func (x *ValidateAdmissionRequest) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *ValidateAdmissionRequest) GetOldObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_OldObjectBytes
	}
	return nil
}

func (x *ValidateAdmissionRequest) SetOperation(v Operation) {
	x.xxx_hidden_Operation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ValidateAdmissionRequest) SetKind(v *GroupVersionKind) {
	x.xxx_hidden_Kind = v
}

func (x *ValidateAdmissionRequest) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ValidateAdmissionRequest) SetOldObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OldObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ValidateAdmissionRequest) HasOperation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValidateAdmissionRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *ValidateAdmissionRequest) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ValidateAdmissionRequest) HasOldObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ValidateAdmissionRequest) ClearOperation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Operation = Operation_OPERATION_UNSPECIFIED
}

func (x *ValidateAdmissionRequest) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *ValidateAdmissionRequest) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ObjectBytes = nil
}

func (x *ValidateAdmissionRequest) ClearOldObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OldObjectBytes = nil
}

type ValidateAdmissionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation is the requested operation.
	Operation *Operation
	// kind is the object kind.
	Kind *GroupVersionKind
	// object_bytes is the object in the request, including the full metadata envelope.
	ObjectBytes []byte
	// old_object_bytes is the object as it currently exists in storage,
	// including the full metadata envelope.
	OldObjectBytes []byte
}

func (b0 ValidateAdmissionRequest_builder) Build() *ValidateAdmissionRequest {
	m0 := &ValidateAdmissionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Operation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Operation = *b.Operation
	}
	x.xxx_hidden_Kind = b.Kind
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	if b.OldObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_OldObjectBytes = b.OldObjectBytes
	}
	return m0
}

// ValidateAdmissionResponse reports whether an object may be admitted.
type ValidateAdmissionResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Allowed     bool                   `protobuf:"varint,1,opt,name=allowed"`
	xxx_hidden_Result      *StatusResult          `protobuf:"bytes,2,opt,name=result"`
	xxx_hidden_Warnings    []string               `protobuf:"bytes,3,rep,name=warnings"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidateAdmissionResponse) Reset() {
	*x = ValidateAdmissionResponse{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAdmissionResponse) ProtoMessage() {}

func (x *ValidateAdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateAdmissionResponse) GetAllowed() bool {
	if x != nil {
		return x.xxx_hidden_Allowed
	}
	return false
}

func (x *ValidateAdmissionResponse) GetResult() *StatusResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *ValidateAdmissionResponse) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *ValidateAdmissionResponse) SetAllowed(v bool) {
	x.xxx_hidden_Allowed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ValidateAdmissionResponse) SetResult(v *StatusResult) {
	x.xxx_hidden_Result = v
}

func (x *ValidateAdmissionResponse) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *ValidateAdmissionResponse) HasAllowed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValidateAdmissionResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *ValidateAdmissionResponse) ClearAllowed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Allowed = false
}

func (x *ValidateAdmissionResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

type ValidateAdmissionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// allowed indicates whether or not the admission request was permitted.
	Allowed *bool
	// result contains extra detail about why an admission request was denied.
	// It is not consulted in any way when allowed is true.
	Result *StatusResult
	// warnings is a list of warning messages to return to the requesting client.
	// Limit warnings to 120 characters if possible. Warnings over 256 characters
	// and large numbers of warnings may be truncated.
	Warnings []string
}

func (b0 ValidateAdmissionResponse_builder) Build() *ValidateAdmissionResponse {
	m0 := &ValidateAdmissionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Allowed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Allowed = *b.Allowed
	}
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Warnings = b.Warnings
	return m0
}

// MutateAdmissionRequest contains information from a Kubernetes admission
// request and the decoded object(s).
type MutateAdmissionRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Operation      Operation              `protobuf:"varint,1,opt,name=operation,enum=grafana.plugin.v3.Operation"`
	xxx_hidden_Kind           *GroupVersionKind      `protobuf:"bytes,2,opt,name=kind"`
	xxx_hidden_ObjectBytes    []byte                 `protobuf:"bytes,3,opt,name=object_bytes,json=objectBytes"`
	xxx_hidden_OldObjectBytes []byte                 `protobuf:"bytes,4,opt,name=old_object_bytes,json=oldObjectBytes"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MutateAdmissionRequest) Reset() {
	*x = MutateAdmissionRequest{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateAdmissionRequest) ProtoMessage() {}

func (x *MutateAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MutateAdmissionRequest) GetOperation() Operation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Operation
		}
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *MutateAdmissionRequest) GetKind() *GroupVersionKind {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return nil
}

func (x *MutateAdmissionRequest) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *MutateAdmissionRequest) GetOldObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_OldObjectBytes
	}
	return nil
}

func (x *MutateAdmissionRequest) SetOperation(v Operation) {
	x.xxx_hidden_Operation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MutateAdmissionRequest) SetKind(v *GroupVersionKind) {
	x.xxx_hidden_Kind = v
}

func (x *MutateAdmissionRequest) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *MutateAdmissionRequest) SetOldObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OldObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *MutateAdmissionRequest) HasOperation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MutateAdmissionRequest) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *MutateAdmissionRequest) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MutateAdmissionRequest) HasOldObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MutateAdmissionRequest) ClearOperation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Operation = Operation_OPERATION_UNSPECIFIED
}

func (x *MutateAdmissionRequest) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *MutateAdmissionRequest) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ObjectBytes = nil
}

func (x *MutateAdmissionRequest) ClearOldObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_OldObjectBytes = nil
}

type MutateAdmissionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// operation is the requested operation.
	Operation *Operation
	// kind is the object kind.
	Kind *GroupVersionKind
	// object_bytes is the object in the request, including the full metadata envelope.
	ObjectBytes []byte
	// old_object_bytes is the object as it currently exists in storage,
	// including the full metadata envelope.
	OldObjectBytes []byte
}

func (b0 MutateAdmissionRequest_builder) Build() *MutateAdmissionRequest {
	m0 := &MutateAdmissionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Operation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Operation = *b.Operation
	}
	x.xxx_hidden_Kind = b.Kind
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	if b.OldObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_OldObjectBytes = b.OldObjectBytes
	}
	return m0
}

// MutateAdmissionResponse returns a mutated copy of the object in a form that
// can be admitted.
type MutateAdmissionResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Allowed     bool                   `protobuf:"varint,1,opt,name=allowed"`
	xxx_hidden_Result      *StatusResult          `protobuf:"bytes,2,opt,name=result"`
	xxx_hidden_Warnings    []string               `protobuf:"bytes,3,rep,name=warnings"`
	xxx_hidden_ObjectBytes []byte                 `protobuf:"bytes,4,opt,name=object_bytes,json=objectBytes"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MutateAdmissionResponse) Reset() {
	*x = MutateAdmissionResponse{}
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateAdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateAdmissionResponse) ProtoMessage() {}

func (x *MutateAdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_admission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MutateAdmissionResponse) GetAllowed() bool {
	if x != nil {
		return x.xxx_hidden_Allowed
	}
	return false
}

func (x *MutateAdmissionResponse) GetResult() *StatusResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *MutateAdmissionResponse) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *MutateAdmissionResponse) GetObjectBytes() []byte {
	if x != nil {
		return x.xxx_hidden_ObjectBytes
	}
	return nil
}

func (x *MutateAdmissionResponse) SetAllowed(v bool) {
	x.xxx_hidden_Allowed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MutateAdmissionResponse) SetResult(v *StatusResult) {
	x.xxx_hidden_Result = v
}

func (x *MutateAdmissionResponse) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *MutateAdmissionResponse) SetObjectBytes(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ObjectBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *MutateAdmissionResponse) HasAllowed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MutateAdmissionResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *MutateAdmissionResponse) HasObjectBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MutateAdmissionResponse) ClearAllowed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Allowed = false
}

func (x *MutateAdmissionResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

func (x *MutateAdmissionResponse) ClearObjectBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ObjectBytes = nil
}

type MutateAdmissionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// allowed indicates whether or not the admission request was permitted.
	Allowed *bool
	// result contains extra detail about why an admission request was denied.
	// It is not consulted in any way when allowed is true.
	Result *StatusResult
	// warnings is a list of warning messages to return to the requesting client.
	Warnings []string
	// object_bytes is the mutated object.
	ObjectBytes []byte
}

func (b0 MutateAdmissionResponse_builder) Build() *MutateAdmissionResponse {
	m0 := &MutateAdmissionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Allowed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Allowed = *b.Allowed
	}
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Warnings = b.Warnings
	if b.ObjectBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ObjectBytes = b.ObjectBytes
	}
	return m0
}

var File_grafana_plugin_v3_admission_proto protoreflect.FileDescriptor

const file_grafana_plugin_v3_admission_proto_rawDesc = "" +
	"\n" +
	"!grafana/plugin/v3/admission.proto\x12\x11grafana.plugin.v3\x1a\x1egrafana/plugin/v3/common.proto\"V\n" +
	"\x10GroupVersionKind\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"\xdc\x01\n" +
	"\x18ValidateAdmissionRequest\x12:\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1c.grafana.plugin.v3.OperationR\toperation\x127\n" +
	"\x04kind\x18\x02 \x01(\v2#.grafana.plugin.v3.GroupVersionKindR\x04kind\x12!\n" +
	"\fobject_bytes\x18\x03 \x01(\fR\vobjectBytes\x12(\n" +
	"\x10old_object_bytes\x18\x04 \x01(\fR\x0eoldObjectBytes\"\x8a\x01\n" +
	"\x19ValidateAdmissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.grafana.plugin.v3.StatusResultR\x06result\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\xda\x01\n" +
	"\x16MutateAdmissionRequest\x12:\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1c.grafana.plugin.v3.OperationR\toperation\x127\n" +
	"\x04kind\x18\x02 \x01(\v2#.grafana.plugin.v3.GroupVersionKindR\x04kind\x12!\n" +
	"\fobject_bytes\x18\x03 \x01(\fR\vobjectBytes\x12(\n" +
	"\x10old_object_bytes\x18\x04 \x01(\fR\x0eoldObjectBytes\"\xab\x01\n" +
	"\x17MutateAdmissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.grafana.plugin.v3.StatusResultR\x06result\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x12!\n" +
	"\fobject_bytes\x18\x04 \x01(\fR\vobjectBytes*h\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x14\n" +
	"\x10OPERATION_UPDATE\x10\x02\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x032\xed\x01\n" +
	"\x17AdmissionControlService\x12k\n" +
	"\x0eValidateObject\x12+.grafana.plugin.v3.ValidateAdmissionRequest\x1a,.grafana.plugin.v3.ValidateAdmissionResponse\x12e\n" +
	"\fMutateObject\x12).grafana.plugin.v3.MutateAdmissionRequest\x1a*.grafana.plugin.v3.MutateAdmissionResponseB\xdb\x01\n" +
	"\x15com.grafana.plugin.v3B\x0eAdmissionProtoP\x01ZLgithub.com/grafana/grafana-plugin-sdk-go/genproto/grafana/plugin/v3;pluginv3\xa2\x02\x03GPX\xaa\x02\x11Grafana.Plugin.V3\xca\x02\x11Grafana\\Plugin\\V3\xe2\x02\x1dGrafana\\Plugin\\V3\\GPBMetadata\xea\x02\x13Grafana::Plugin::V3b\beditionsp\xe9\a"

var file_grafana_plugin_v3_admission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grafana_plugin_v3_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grafana_plugin_v3_admission_proto_goTypes = []any{
	(Operation)(0),                    // 0: grafana.plugin.v3.Operation
	(*GroupVersionKind)(nil),          // 1: grafana.plugin.v3.GroupVersionKind
	(*ValidateAdmissionRequest)(nil),  // 2: grafana.plugin.v3.ValidateAdmissionRequest
	(*ValidateAdmissionResponse)(nil), // 3: grafana.plugin.v3.ValidateAdmissionResponse
	(*MutateAdmissionRequest)(nil),    // 4: grafana.plugin.v3.MutateAdmissionRequest
	(*MutateAdmissionResponse)(nil),   // 5: grafana.plugin.v3.MutateAdmissionResponse
	(*StatusResult)(nil),              // 6: grafana.plugin.v3.StatusResult
}
var file_grafana_plugin_v3_admission_proto_depIdxs = []int32{
	0, // 0: grafana.plugin.v3.ValidateAdmissionRequest.operation:type_name -> grafana.plugin.v3.Operation
	1, // 1: grafana.plugin.v3.ValidateAdmissionRequest.kind:type_name -> grafana.plugin.v3.GroupVersionKind
	6, // 2: grafana.plugin.v3.ValidateAdmissionResponse.result:type_name -> grafana.plugin.v3.StatusResult
	0, // 3: grafana.plugin.v3.MutateAdmissionRequest.operation:type_name -> grafana.plugin.v3.Operation
	1, // 4: grafana.plugin.v3.MutateAdmissionRequest.kind:type_name -> grafana.plugin.v3.GroupVersionKind
	6, // 5: grafana.plugin.v3.MutateAdmissionResponse.result:type_name -> grafana.plugin.v3.StatusResult
	2, // 6: grafana.plugin.v3.AdmissionControlService.ValidateObject:input_type -> grafana.plugin.v3.ValidateAdmissionRequest
	4, // 7: grafana.plugin.v3.AdmissionControlService.MutateObject:input_type -> grafana.plugin.v3.MutateAdmissionRequest
	3, // 8: grafana.plugin.v3.AdmissionControlService.ValidateObject:output_type -> grafana.plugin.v3.ValidateAdmissionResponse
	5, // 9: grafana.plugin.v3.AdmissionControlService.MutateObject:output_type -> grafana.plugin.v3.MutateAdmissionResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_grafana_plugin_v3_admission_proto_init() }
func file_grafana_plugin_v3_admission_proto_init() {
	if File_grafana_plugin_v3_admission_proto != nil {
		return
	}
	file_grafana_plugin_v3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_plugin_v3_admission_proto_rawDesc), len(file_grafana_plugin_v3_admission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grafana_plugin_v3_admission_proto_goTypes,
		DependencyIndexes: file_grafana_plugin_v3_admission_proto_depIdxs,
		EnumInfos:         file_grafana_plugin_v3_admission_proto_enumTypes,
		MessageInfos:      file_grafana_plugin_v3_admission_proto_msgTypes,
	}.Build()
	File_grafana_plugin_v3_admission_proto = out.File
	file_grafana_plugin_v3_admission_proto_goTypes = nil
	file_grafana_plugin_v3_admission_proto_depIdxs = nil
}
