// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grafana/plugin/v3/conversion.proto

package pluginv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawObject contains a resource serialized into a byte array with a content
// type.
type RawObject struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Raw         []byte                 `protobuf:"bytes,1,opt,name=raw"`
	xxx_hidden_ContentType *string                `protobuf:"bytes,2,opt,name=content_type,json=contentType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RawObject) Reset() {
	*x = RawObject{}
	mi := &file_grafana_plugin_v3_conversion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawObject) ProtoMessage() {}

func (x *RawObject) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_conversion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RawObject) GetRaw() []byte {
	if x != nil {
		return x.xxx_hidden_Raw
	}
	return nil
}

func (x *RawObject) GetContentType() string {
	if x != nil {
		if x.xxx_hidden_ContentType != nil {
			return *x.xxx_hidden_ContentType
		}
		return ""
	}
	return ""
}

func (x *RawObject) SetRaw(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Raw = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RawObject) SetContentType(v string) {
	x.xxx_hidden_ContentType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RawObject) HasRaw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RawObject) HasContentType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RawObject) ClearRaw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Raw = nil
}

func (x *RawObject) ClearContentType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ContentType = nil
}

type RawObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// raw is the serialized object.
	Raw []byte
	// content_type is the media type of the raw object.
	ContentType *string
}

func (b0 RawObject_builder) Build() *RawObject {
	m0 := &RawObject{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Raw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Raw = b.Raw
	}
	if b.ContentType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ContentType = b.ContentType
	}
	return m0
}

// ConvertObjectsRequest supports converting objects from one version to
// another.
type ConvertObjectsRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ApiVersion    *GroupVersion          `protobuf:"bytes,1,opt,name=api_version,json=apiVersion"`
	xxx_hidden_Uid           *string                `protobuf:"bytes,2,opt,name=uid"`
	xxx_hidden_Objects       *[]*RawObject          `protobuf:"bytes,3,rep,name=objects"`
	xxx_hidden_TargetVersion *GroupVersion          `protobuf:"bytes,4,opt,name=target_version,json=targetVersion"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConvertObjectsRequest) Reset() {
	*x = ConvertObjectsRequest{}
	mi := &file_grafana_plugin_v3_conversion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertObjectsRequest) ProtoMessage() {}

func (x *ConvertObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_conversion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConvertObjectsRequest) GetApiVersion() *GroupVersion {
	if x != nil {
		return x.xxx_hidden_ApiVersion
	}
	return nil
}

func (x *ConvertObjectsRequest) GetUid() string {
	if x != nil {
		if x.xxx_hidden_Uid != nil {
			return *x.xxx_hidden_Uid
		}
		return ""
	}
	return ""
}

func (x *ConvertObjectsRequest) GetObjects() []*RawObject {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *ConvertObjectsRequest) GetTargetVersion() *GroupVersion {
	if x != nil {
		return x.xxx_hidden_TargetVersion
	}
	return nil
}

func (x *ConvertObjectsRequest) SetApiVersion(v *GroupVersion) {
	x.xxx_hidden_ApiVersion = v
}

func (x *ConvertObjectsRequest) SetUid(v string) {
	x.xxx_hidden_Uid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ConvertObjectsRequest) SetObjects(v []*RawObject) {
	x.xxx_hidden_Objects = &v
}

func (x *ConvertObjectsRequest) SetTargetVersion(v *GroupVersion) {
	x.xxx_hidden_TargetVersion = v
}

func (x *ConvertObjectsRequest) HasApiVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ApiVersion != nil
}

func (x *ConvertObjectsRequest) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConvertObjectsRequest) HasTargetVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetVersion != nil
}

func (x *ConvertObjectsRequest) ClearApiVersion() {
	x.xxx_hidden_ApiVersion = nil
}

func (x *ConvertObjectsRequest) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Uid = nil
}

func (x *ConvertObjectsRequest) ClearTargetVersion() {
	x.xxx_hidden_TargetVersion = nil
}

type ConvertObjectsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// the request api_version
	ApiVersion *GroupVersion
	// uid is an identifier for the individual request/response. It allows
	// distinguishing instances of requests which are otherwise identical
	// (parallel requests, etc). It is meant to track the round trip between the
	// Kubernetes API server and the webhook, not the user request.
	Uid *string
	// objects to convert.
	Objects []*RawObject
	// target_version is the version to convert to.
	TargetVersion *GroupVersion
}

func (b0 ConvertObjectsRequest_builder) Build() *ConvertObjectsRequest {
	m0 := &ConvertObjectsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ApiVersion = b.ApiVersion
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Uid = b.Uid
	}
	x.xxx_hidden_Objects = &b.Objects
	x.xxx_hidden_TargetVersion = b.TargetVersion
	return m0
}

// ConvertObjectsResponse contains the converted objects.
type ConvertObjectsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uid         *string                `protobuf:"bytes,1,opt,name=uid"`
	xxx_hidden_Result      *StatusResult          `protobuf:"bytes,2,opt,name=result"`
	xxx_hidden_Objects     *[]*RawObject          `protobuf:"bytes,3,rep,name=objects"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConvertObjectsResponse) Reset() {
	*x = ConvertObjectsResponse{}
	mi := &file_grafana_plugin_v3_conversion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertObjectsResponse) ProtoMessage() {}

func (x *ConvertObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grafana_plugin_v3_conversion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConvertObjectsResponse) GetUid() string {
	if x != nil {
		if x.xxx_hidden_Uid != nil {
			return *x.xxx_hidden_Uid
		}
		return ""
	}
	return ""
}

func (x *ConvertObjectsResponse) GetResult() *StatusResult {
	if x != nil {
		return x.xxx_hidden_Result
	}
	return nil
}

func (x *ConvertObjectsResponse) GetObjects() []*RawObject {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *ConvertObjectsResponse) SetUid(v string) {
	x.xxx_hidden_Uid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ConvertObjectsResponse) SetResult(v *StatusResult) {
	x.xxx_hidden_Result = v
}

func (x *ConvertObjectsResponse) SetObjects(v []*RawObject) {
	x.xxx_hidden_Objects = &v
}

func (x *ConvertObjectsResponse) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConvertObjectsResponse) HasResult() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Result != nil
}

func (x *ConvertObjectsResponse) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uid = nil
}

func (x *ConvertObjectsResponse) ClearResult() {
	x.xxx_hidden_Result = nil
}

type ConvertObjectsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// uid is an identifier for the individual request/response. This should be
	// copied over from the corresponding request.uid.
	Uid *string
	// result contains extra detail into why a request was denied.
	Result *StatusResult
	// objects is the converted version of request.objects if result is
	// successful, otherwise empty.
	Objects []*RawObject
}

func (b0 ConvertObjectsResponse_builder) Build() *ConvertObjectsResponse {
	m0 := &ConvertObjectsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Uid = b.Uid
	}
	x.xxx_hidden_Result = b.Result
	x.xxx_hidden_Objects = &b.Objects
	return m0
}

var File_grafana_plugin_v3_conversion_proto protoreflect.FileDescriptor

const file_grafana_plugin_v3_conversion_proto_rawDesc = "" +
	"\n" +
	"\"grafana/plugin/v3/conversion.proto\x12\x11grafana.plugin.v3\x1a\x1egrafana/plugin/v3/common.proto\"@\n" +
	"\tRawObject\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xeb\x01\n" +
	"\x15ConvertObjectsRequest\x12@\n" +
	"\vapi_version\x18\x01 \x01(\v2\x1f.grafana.plugin.v3.GroupVersionR\n" +
	"apiVersion\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x126\n" +
	"\aobjects\x18\x03 \x03(\v2\x1c.grafana.plugin.v3.RawObjectR\aobjects\x12F\n" +
	"\x0etarget_version\x18\x04 \x01(\v2\x1f.grafana.plugin.v3.GroupVersionR\rtargetVersion\"\x9b\x01\n" +
	"\x16ConvertObjectsResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1f.grafana.plugin.v3.StatusResultR\x06result\x126\n" +
	"\aobjects\x18\x03 \x03(\v2\x1c.grafana.plugin.v3.RawObjectR\aobjects2\x82\x01\n" +
	"\x19ResourceConversionService\x12e\n" +
	"\x0eConvertObjects\x12(.grafana.plugin.v3.ConvertObjectsRequest\x1a).grafana.plugin.v3.ConvertObjectsResponseB\xdc\x01\n" +
	"\x15com.grafana.plugin.v3B\x0fConversionProtoP\x01ZLgithub.com/grafana/grafana-plugin-sdk-go/genproto/grafana/plugin/v3;pluginv3\xa2\x02\x03GPX\xaa\x02\x11Grafana.Plugin.V3\xca\x02\x11Grafana\\Plugin\\V3\xe2\x02\x1dGrafana\\Plugin\\V3\\GPBMetadata\xea\x02\x13Grafana::Plugin::V3b\beditionsp\xe9\a"

var file_grafana_plugin_v3_conversion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grafana_plugin_v3_conversion_proto_goTypes = []any{
	(*RawObject)(nil),              // 0: grafana.plugin.v3.RawObject
	(*ConvertObjectsRequest)(nil),  // 1: grafana.plugin.v3.ConvertObjectsRequest
	(*ConvertObjectsResponse)(nil), // 2: grafana.plugin.v3.ConvertObjectsResponse
	(*GroupVersion)(nil),           // 3: grafana.plugin.v3.GroupVersion
	(*StatusResult)(nil),           // 4: grafana.plugin.v3.StatusResult
}
var file_grafana_plugin_v3_conversion_proto_depIdxs = []int32{
	3, // 0: grafana.plugin.v3.ConvertObjectsRequest.api_version:type_name -> grafana.plugin.v3.GroupVersion
	0, // 1: grafana.plugin.v3.ConvertObjectsRequest.objects:type_name -> grafana.plugin.v3.RawObject
	3, // 2: grafana.plugin.v3.ConvertObjectsRequest.target_version:type_name -> grafana.plugin.v3.GroupVersion
	4, // 3: grafana.plugin.v3.ConvertObjectsResponse.result:type_name -> grafana.plugin.v3.StatusResult
	0, // 4: grafana.plugin.v3.ConvertObjectsResponse.objects:type_name -> grafana.plugin.v3.RawObject
	1, // 5: grafana.plugin.v3.ResourceConversionService.ConvertObjects:input_type -> grafana.plugin.v3.ConvertObjectsRequest
	2, // 6: grafana.plugin.v3.ResourceConversionService.ConvertObjects:output_type -> grafana.plugin.v3.ConvertObjectsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grafana_plugin_v3_conversion_proto_init() }
func file_grafana_plugin_v3_conversion_proto_init() {
	if File_grafana_plugin_v3_conversion_proto != nil {
		return
	}
	file_grafana_plugin_v3_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grafana_plugin_v3_conversion_proto_rawDesc), len(file_grafana_plugin_v3_conversion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grafana_plugin_v3_conversion_proto_goTypes,
		DependencyIndexes: file_grafana_plugin_v3_conversion_proto_depIdxs,
		MessageInfos:      file_grafana_plugin_v3_conversion_proto_msgTypes,
	}.Build()
	File_grafana_plugin_v3_conversion_proto = out.File
	file_grafana_plugin_v3_conversion_proto_goTypes = nil
	file_grafana_plugin_v3_conversion_proto_depIdxs = nil
}
