---
# This file must be signed. You can do so with the `mage drone` command

kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

services:
  - image: mysql:8.0
    name: "mysql"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

trigger:
  branch: main
  event:
  - push

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v testRace

- name: integration_tests
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  environment:
    INTEGRATION_TESTS: "true"
    MYSQL_URL: "mysql:mysql@tcp(mysql:3306)/mysql"
  commands:
    - mage -v test
---
kind: pipeline
type: docker
name: pr

platform:
  os: linux
  arch: amd64

services:
  - image: mysql:8.0
    name: "mysql"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

trigger:
  event:
  - pull_request

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v testRace

- name: integration_tests
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  environment:
    INTEGRATION_TESTS: "true"
    MYSQL_URL: "mysql:mysql@tcp(mysql:3306)/mysql"
  commands:
    - mage -v test

---
kind: signature
hmac: 329582f349b7f3a2bc25d2848d2bc3bd6232a66d1596e73b7c7317eac2a50d7e

...
