---
# This file must be signed. You can do so with the `mage drone` command

kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

trigger:
  branch: main
  event:
  - push

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v testRace
---
kind: pipeline
type: docker
name: pr

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - pull_request

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.6.1-alpine
  commands:
  - mage -v testRace

---
kind: signature
hmac: 329582f349b7f3a2bc25d2848d2bc3bd6232a66d1596e73b7c7317eac2a50d7e

...
