---
# This file must be signed. You can do so with the `mage drone` command

kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

trigger:
  branch: main
  event:
  - push

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.9.5
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.9.5
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.9.5
  commands:
  - mage -v testRace
---
kind: pipeline
type: docker
name: pr

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - pull_request

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.9.5
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.9.5
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.9.5
  commands:
  - mage -v testRace

---
kind: signature
hmac: b7ab5d7df4753837c999e7502e27ed73fc23448500960a34e3ed68f3776cc067

...
