---
# This file must be signed. You can do so with the `mage drone` command

kind: pipeline
type: docker
name: main

platform:
  os: linux
  arch: amd64

trigger:
  branch: main
  event:
  - push

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.9.6
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.9.6
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.9.6
  commands:
  # -race requires cgo + a C compiler
  - apt update
  - apt install -y gcc
  - mage -v testRace
  environment:
    CGO_ENABLED: "1"
---
kind: pipeline
type: docker
name: pr

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - pull_request

steps:
- name: build
  image: grafana/grafana-plugin-ci:1.9.6
  commands:
  - mage -v build

- name: lint
  image: grafana/grafana-plugin-ci:1.9.6
  commands:
  - mage -v lint

- name: test
  image: grafana/grafana-plugin-ci:1.9.6
  commands:
  # -race requires cgo + a C compiler
  - apt update
  - apt install -y gcc
  - mage -v testRace
  environment:
    CGO_ENABLED: "1"

---
kind: signature
hmac: 65417116eafb288e3627e0a618d2d88e7fb71527517f3a9ddfbdd032eb654511

...
