// Code generated by wit-bindgen-go. DO NOT EDIT.

package querydata

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "grafana:plugins/query-data@0.1.0".
var Exports struct {
	// RunQuery represents the caller-defined, exported function "run-query".
	//
	//	run-query: func(request: query-data-request) -> result<query-data-response>
	RunQuery func(request QueryDataRequest) (result cm.Result[QueryDataResponse, QueryDataResponse, struct{}])
}
