// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package querydata represents the exported interface "grafana:plugins/query-data@0.1.0".
package querydata

import (
	"github.com/grafana/grafana-plugin-sdk-go/genwit/grafana/plugins/types"
)

// QueryDataRequest represents the type alias "grafana:plugins/query-data@0.1.0#query-data-request".
//
// See [types.QueryDataRequest] for more information.
type QueryDataRequest = types.QueryDataRequest

// QueryDataResponse represents the type alias "grafana:plugins/query-data@0.1.0#query-data-response".
//
// See [types.QueryDataResponse] for more information.
type QueryDataResponse = types.QueryDataResponse
