// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "grafana:plugins/types@0.1.0".
package types

import (
	"go.bytecodealliance.org/cm"
)

// PluginContext represents the record "grafana:plugins/types@0.1.0#plugin-context".
//
//	record plugin-context {
//		org-id: s64,
//	}
type PluginContext struct {
	_     cm.HostLayout `json:"-"`
	OrgID int64         `json:"org-id"`
}

// QueryDataRequest represents the record "grafana:plugins/types@0.1.0#query-data-request".
//
//	record query-data-request {
//		plugin-context: plugin-context,
//	}
type QueryDataRequest struct {
	_             cm.HostLayout `json:"-"`
	PluginContext PluginContext `json:"plugin-context"`
}

// DataResponse represents the record "grafana:plugins/types@0.1.0#data-response".
//
//	record data-response {
//		frames: list<list<u8>>,
//	}
type DataResponse struct {
	_      cm.HostLayout           `json:"-"`
	Frames cm.List[cm.List[uint8]] `json:"frames"`
}

// QueryDataResponse represents the record "grafana:plugins/types@0.1.0#query-data-response".
//
//	record query-data-response {
//		responses: list<tuple<string, data-response>>,
//	}
type QueryDataResponse struct {
	_         cm.HostLayout                           `json:"-"`
	Responses cm.List[cm.Tuple[string, DataResponse]] `json:"responses"`
}
