// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package grafana_plugin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PluginStatusRequest_FetchInfo int32

const (
	PluginStatusRequest_STATUS  PluginStatusRequest_FetchInfo = 0
	PluginStatusRequest_API     PluginStatusRequest_FetchInfo = 1
	PluginStatusRequest_METRICS PluginStatusRequest_FetchInfo = 2
	PluginStatusRequest_DEBUG   PluginStatusRequest_FetchInfo = 3
)

var PluginStatusRequest_FetchInfo_name = map[int32]string{
	0: "STATUS",
	1: "API",
	2: "METRICS",
	3: "DEBUG",
}

var PluginStatusRequest_FetchInfo_value = map[string]int32{
	"STATUS":  0,
	"API":     1,
	"METRICS": 2,
	"DEBUG":   3,
}

func (x PluginStatusRequest_FetchInfo) String() string {
	return proto.EnumName(PluginStatusRequest_FetchInfo_name, int32(x))
}

func (PluginStatusRequest_FetchInfo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1, 0}
}

type PluginStatusResponse_PluginStatus int32

const (
	PluginStatusResponse_UNKNOWN PluginStatusResponse_PluginStatus = 0
	PluginStatusResponse_OK      PluginStatusResponse_PluginStatus = 1
	PluginStatusResponse_ERROR   PluginStatusResponse_PluginStatus = 2
)

var PluginStatusResponse_PluginStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "ERROR",
}

var PluginStatusResponse_PluginStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"OK":      1,
	"ERROR":   2,
}

func (x PluginStatusResponse_PluginStatus) String() string {
	return proto.EnumName(PluginStatusResponse_PluginStatus_name, int32(x))
}

func (PluginStatusResponse_PluginStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{2, 0}
}

type PluginConfig struct {
	Id                      int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId                   int64             `protobuf:"varint,2,opt,name=orgId,proto3" json:"orgId,omitempty"`
	Name                    string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                    string            `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Url                     string            `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	JsonData                string            `protobuf:"bytes,6,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	DecryptedSecureJsonData map[string]string `protobuf:"bytes,7,rep,name=decryptedSecureJsonData,proto3" json:"decryptedSecureJsonData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral    struct{}          `json:"-"`
	XXX_unrecognized        []byte            `json:"-"`
	XXX_sizecache           int32             `json:"-"`
}

func (m *PluginConfig) Reset()         { *m = PluginConfig{} }
func (m *PluginConfig) String() string { return proto.CompactTextString(m) }
func (*PluginConfig) ProtoMessage()    {}
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{0}
}

func (m *PluginConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfig.Unmarshal(m, b)
}
func (m *PluginConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfig.Marshal(b, m, deterministic)
}
func (m *PluginConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfig.Merge(m, src)
}
func (m *PluginConfig) XXX_Size() int {
	return xxx_messageInfo_PluginConfig.Size(m)
}
func (m *PluginConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfig proto.InternalMessageInfo

func (m *PluginConfig) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PluginConfig) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *PluginConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PluginConfig) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PluginConfig) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

func (m *PluginConfig) GetDecryptedSecureJsonData() map[string]string {
	if m != nil {
		return m.DecryptedSecureJsonData
	}
	return nil
}

type PluginStatusRequest struct {
	// Plugin Configuration
	Config *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Environment info
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Get an OpenAPI description (viewer+)
	Fetch                PluginStatusRequest_FetchInfo `protobuf:"varint,3,opt,name=fetch,proto3,enum=grafana.plugin.PluginStatusRequest_FetchInfo" json:"fetch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PluginStatusRequest) Reset()         { *m = PluginStatusRequest{} }
func (m *PluginStatusRequest) String() string { return proto.CompactTextString(m) }
func (*PluginStatusRequest) ProtoMessage()    {}
func (*PluginStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1}
}

func (m *PluginStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginStatusRequest.Unmarshal(m, b)
}
func (m *PluginStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginStatusRequest.Marshal(b, m, deterministic)
}
func (m *PluginStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginStatusRequest.Merge(m, src)
}
func (m *PluginStatusRequest) XXX_Size() int {
	return xxx_messageInfo_PluginStatusRequest.Size(m)
}
func (m *PluginStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PluginStatusRequest proto.InternalMessageInfo

func (m *PluginStatusRequest) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *PluginStatusRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *PluginStatusRequest) GetFetch() PluginStatusRequest_FetchInfo {
	if m != nil {
		return m.Fetch
	}
	return PluginStatusRequest_STATUS
}

type PluginStatusResponse struct {
	Status               PluginStatusResponse_PluginStatus `protobuf:"varint,1,opt,name=status,proto3,enum=grafana.plugin.PluginStatusResponse_PluginStatus" json:"status,omitempty"`
	Info                 string                            `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *PluginStatusResponse) Reset()         { *m = PluginStatusResponse{} }
func (m *PluginStatusResponse) String() string { return proto.CompactTextString(m) }
func (*PluginStatusResponse) ProtoMessage()    {}
func (*PluginStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{2}
}

func (m *PluginStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginStatusResponse.Unmarshal(m, b)
}
func (m *PluginStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginStatusResponse.Marshal(b, m, deterministic)
}
func (m *PluginStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginStatusResponse.Merge(m, src)
}
func (m *PluginStatusResponse) XXX_Size() int {
	return xxx_messageInfo_PluginStatusResponse.Size(m)
}
func (m *PluginStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PluginStatusResponse proto.InternalMessageInfo

func (m *PluginStatusResponse) GetStatus() PluginStatusResponse_PluginStatus {
	if m != nil {
		return m.Status
	}
	return PluginStatusResponse_UNKNOWN
}

func (m *PluginStatusResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type TimeRange struct {
	FromRaw              string   `protobuf:"bytes,1,opt,name=fromRaw,proto3" json:"fromRaw,omitempty"`
	ToRaw                string   `protobuf:"bytes,2,opt,name=toRaw,proto3" json:"toRaw,omitempty"`
	FromEpochMS          int64    `protobuf:"varint,3,opt,name=fromEpochMS,proto3" json:"fromEpochMS,omitempty"`
	ToEpochMS            int64    `protobuf:"varint,4,opt,name=toEpochMS,proto3" json:"toEpochMS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{3}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetFromRaw() string {
	if m != nil {
		return m.FromRaw
	}
	return ""
}

func (m *TimeRange) GetToRaw() string {
	if m != nil {
		return m.ToRaw
	}
	return ""
}

func (m *TimeRange) GetFromEpochMS() int64 {
	if m != nil {
		return m.FromEpochMS
	}
	return 0
}

func (m *TimeRange) GetToEpochMS() int64 {
	if m != nil {
		return m.ToEpochMS
	}
	return 0
}

type DataQuery struct {
	RefId                string     `protobuf:"bytes,1,opt,name=refId,proto3" json:"refId,omitempty"`
	MaxDataPoints        int64      `protobuf:"varint,2,opt,name=maxDataPoints,proto3" json:"maxDataPoints,omitempty"`
	IntervalMS           int64      `protobuf:"varint,3,opt,name=intervalMS,proto3" json:"intervalMS,omitempty"`
	TimeRange            *TimeRange `protobuf:"bytes,4,opt,name=timeRange,proto3" json:"timeRange,omitempty"`
	Json                 []byte     `protobuf:"bytes,5,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataQuery) Reset()         { *m = DataQuery{} }
func (m *DataQuery) String() string { return proto.CompactTextString(m) }
func (*DataQuery) ProtoMessage()    {}
func (*DataQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{4}
}

func (m *DataQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQuery.Unmarshal(m, b)
}
func (m *DataQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQuery.Marshal(b, m, deterministic)
}
func (m *DataQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQuery.Merge(m, src)
}
func (m *DataQuery) XXX_Size() int {
	return xxx_messageInfo_DataQuery.Size(m)
}
func (m *DataQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DataQuery proto.InternalMessageInfo

func (m *DataQuery) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *DataQuery) GetMaxDataPoints() int64 {
	if m != nil {
		return m.MaxDataPoints
	}
	return 0
}

func (m *DataQuery) GetIntervalMS() int64 {
	if m != nil {
		return m.IntervalMS
	}
	return 0
}

func (m *DataQuery) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *DataQuery) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

type DataQueryRequest struct {
	// Plugin Configuration
	Config *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Environment info
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// List of queries
	Queries              []*DataQuery `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DataQueryRequest) Reset()         { *m = DataQueryRequest{} }
func (m *DataQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DataQueryRequest) ProtoMessage()    {}
func (*DataQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{5}
}

func (m *DataQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryRequest.Unmarshal(m, b)
}
func (m *DataQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryRequest.Marshal(b, m, deterministic)
}
func (m *DataQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryRequest.Merge(m, src)
}
func (m *DataQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DataQueryRequest.Size(m)
}
func (m *DataQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryRequest proto.InternalMessageInfo

func (m *DataQueryRequest) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *DataQueryRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *DataQueryRequest) GetQueries() []*DataQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

type DataQueryResponse struct {
	// Arrow encoded DataFrames
	// Each frame encodes its own: Errors, meta, and refId
	Frames [][]byte `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	// Additional response metadata
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataQueryResponse) Reset()         { *m = DataQueryResponse{} }
func (m *DataQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DataQueryResponse) ProtoMessage()    {}
func (*DataQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{6}
}

func (m *DataQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryResponse.Unmarshal(m, b)
}
func (m *DataQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryResponse.Marshal(b, m, deterministic)
}
func (m *DataQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryResponse.Merge(m, src)
}
func (m *DataQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DataQueryResponse.Size(m)
}
func (m *DataQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryResponse proto.InternalMessageInfo

func (m *DataQueryResponse) GetFrames() [][]byte {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *DataQueryResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ResourceRequest struct {
	// Plugin Configuration
	Config *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// HTTP Style parameters
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Method               string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string            `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResourceRequest) Reset()         { *m = ResourceRequest{} }
func (m *ResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceRequest) ProtoMessage()    {}
func (*ResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7}
}

func (m *ResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceRequest.Unmarshal(m, b)
}
func (m *ResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceRequest.Marshal(b, m, deterministic)
}
func (m *ResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceRequest.Merge(m, src)
}
func (m *ResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceRequest.Size(m)
}
func (m *ResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceRequest proto.InternalMessageInfo

func (m *ResourceRequest) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ResourceRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ResourceRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ResourceRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ResourceRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ResourceResponse struct {
	Code                 int32             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResourceResponse) Reset()         { *m = ResourceResponse{} }
func (m *ResourceResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceResponse) ProtoMessage()    {}
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8}
}

func (m *ResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceResponse.Unmarshal(m, b)
}
func (m *ResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceResponse.Marshal(b, m, deterministic)
}
func (m *ResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceResponse.Merge(m, src)
}
func (m *ResourceResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceResponse.Size(m)
}
func (m *ResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceResponse proto.InternalMessageInfo

func (m *ResourceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResourceResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ResourceResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type StreamingRequest struct {
	PluginId int64 `protobuf:"varint,1,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	// Environment info
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The topic we are talking to
	Topic string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// The message
	Body string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// Flag if the user is already listening
	Subscribed           bool     `protobuf:"varint,5,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingRequest) Reset()         { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()    {}
func (*StreamingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9}
}

func (m *StreamingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingRequest.Unmarshal(m, b)
}
func (m *StreamingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingRequest.Marshal(b, m, deterministic)
}
func (m *StreamingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingRequest.Merge(m, src)
}
func (m *StreamingRequest) XXX_Size() int {
	return xxx_messageInfo_StreamingRequest.Size(m)
}
func (m *StreamingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingRequest proto.InternalMessageInfo

func (m *StreamingRequest) GetPluginId() int64 {
	if m != nil {
		return m.PluginId
	}
	return 0
}

func (m *StreamingRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *StreamingRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *StreamingRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *StreamingRequest) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

type StreamingMessage struct {
	PluginId             int64    `protobuf:"varint,1,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingMessage) Reset()         { *m = StreamingMessage{} }
func (m *StreamingMessage) String() string { return proto.CompactTextString(m) }
func (*StreamingMessage) ProtoMessage()    {}
func (*StreamingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{10}
}

func (m *StreamingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingMessage.Unmarshal(m, b)
}
func (m *StreamingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingMessage.Marshal(b, m, deterministic)
}
func (m *StreamingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingMessage.Merge(m, src)
}
func (m *StreamingMessage) XXX_Size() int {
	return xxx_messageInfo_StreamingMessage.Size(m)
}
func (m *StreamingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingMessage proto.InternalMessageInfo

func (m *StreamingMessage) GetPluginId() int64 {
	if m != nil {
		return m.PluginId
	}
	return 0
}

func (m *StreamingMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *StreamingMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StreamingClose struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamingClose) Reset()         { *m = StreamingClose{} }
func (m *StreamingClose) String() string { return proto.CompactTextString(m) }
func (*StreamingClose) ProtoMessage()    {}
func (*StreamingClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{11}
}

func (m *StreamingClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingClose.Unmarshal(m, b)
}
func (m *StreamingClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingClose.Marshal(b, m, deterministic)
}
func (m *StreamingClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingClose.Merge(m, src)
}
func (m *StreamingClose) XXX_Size() int {
	return xxx_messageInfo_StreamingClose.Size(m)
}
func (m *StreamingClose) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingClose.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingClose proto.InternalMessageInfo

func (m *StreamingClose) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RenderRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Timezone             string   `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Encoding             string   `protobuf:"bytes,6,opt,name=encoding,proto3" json:"encoding,omitempty"`
	FilePath             string   `protobuf:"bytes,7,opt,name=filePath,proto3" json:"filePath,omitempty"`
	RenderKey            string   `protobuf:"bytes,8,opt,name=renderKey,proto3" json:"renderKey,omitempty"`
	Domain               string   `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	Debug                bool     `protobuf:"varint,10,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderRequest) Reset()         { *m = RenderRequest{} }
func (m *RenderRequest) String() string { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()    {}
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{12}
}

func (m *RenderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderRequest.Unmarshal(m, b)
}
func (m *RenderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderRequest.Marshal(b, m, deterministic)
}
func (m *RenderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderRequest.Merge(m, src)
}
func (m *RenderRequest) XXX_Size() int {
	return xxx_messageInfo_RenderRequest.Size(m)
}
func (m *RenderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenderRequest proto.InternalMessageInfo

func (m *RenderRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RenderRequest) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *RenderRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RenderRequest) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RenderRequest) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *RenderRequest) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *RenderRequest) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *RenderRequest) GetRenderKey() string {
	if m != nil {
		return m.RenderKey
	}
	return ""
}

func (m *RenderRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RenderRequest) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type RenderResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenderResponse) Reset()         { *m = RenderResponse{} }
func (m *RenderResponse) String() string { return proto.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()    {}
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{13}
}

func (m *RenderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenderResponse.Unmarshal(m, b)
}
func (m *RenderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenderResponse.Marshal(b, m, deterministic)
}
func (m *RenderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenderResponse.Merge(m, src)
}
func (m *RenderResponse) XXX_Size() int {
	return xxx_messageInfo_RenderResponse.Size(m)
}
func (m *RenderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenderResponse proto.InternalMessageInfo

func (m *RenderResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("grafana.plugin.PluginStatusRequest_FetchInfo", PluginStatusRequest_FetchInfo_name, PluginStatusRequest_FetchInfo_value)
	proto.RegisterEnum("grafana.plugin.PluginStatusResponse_PluginStatus", PluginStatusResponse_PluginStatus_name, PluginStatusResponse_PluginStatus_value)
	proto.RegisterType((*PluginConfig)(nil), "grafana.plugin.PluginConfig")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.PluginConfig.DecryptedSecureJsonDataEntry")
	proto.RegisterType((*PluginStatusRequest)(nil), "grafana.plugin.PluginStatusRequest")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.PluginStatusRequest.HeadersEntry")
	proto.RegisterType((*PluginStatusResponse)(nil), "grafana.plugin.PluginStatusResponse")
	proto.RegisterType((*TimeRange)(nil), "grafana.plugin.TimeRange")
	proto.RegisterType((*DataQuery)(nil), "grafana.plugin.DataQuery")
	proto.RegisterType((*DataQueryRequest)(nil), "grafana.plugin.DataQueryRequest")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.DataQueryRequest.HeadersEntry")
	proto.RegisterType((*DataQueryResponse)(nil), "grafana.plugin.DataQueryResponse")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.DataQueryResponse.MetadataEntry")
	proto.RegisterType((*ResourceRequest)(nil), "grafana.plugin.ResourceRequest")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.ResourceRequest.HeadersEntry")
	proto.RegisterType((*ResourceResponse)(nil), "grafana.plugin.ResourceResponse")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.ResourceResponse.HeadersEntry")
	proto.RegisterType((*StreamingRequest)(nil), "grafana.plugin.StreamingRequest")
	proto.RegisterMapType((map[string]string)(nil), "grafana.plugin.StreamingRequest.HeadersEntry")
	proto.RegisterType((*StreamingMessage)(nil), "grafana.plugin.StreamingMessage")
	proto.RegisterType((*StreamingClose)(nil), "grafana.plugin.StreamingClose")
	proto.RegisterType((*RenderRequest)(nil), "grafana.plugin.RenderRequest")
	proto.RegisterType((*RenderResponse)(nil), "grafana.plugin.RenderResponse")
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5) }

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 1219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcf, 0x6f, 0x1b, 0xc5,
	0x17, 0xef, 0xae, 0x63, 0x3b, 0x7e, 0xf9, 0x51, 0x7f, 0xe7, 0x1b, 0xca, 0xd6, 0x94, 0x62, 0x4c,
	0x85, 0x72, 0x00, 0xb7, 0xb8, 0x48, 0x94, 0x72, 0x6a, 0x93, 0x34, 0xb8, 0x51, 0x5a, 0x33, 0x4e,
	0x85, 0xd4, 0x03, 0xd2, 0x7a, 0xf7, 0x79, 0xbd, 0xd4, 0xbb, 0xe3, 0xce, 0xce, 0xb6, 0x18, 0x6e,
	0x88, 0x0b, 0xe2, 0xef, 0xe0, 0x3f, 0x80, 0x33, 0x67, 0xc4, 0x8d, 0x7f, 0x85, 0x33, 0x12, 0x9a,
	0x5f, 0x1b, 0xdb, 0xa9, 0x93, 0x54, 0xe9, 0xed, 0xbd, 0x37, 0x33, 0x6f, 0x3f, 0x9f, 0xf7, 0x6b,
	0x66, 0x61, 0x63, 0xe0, 0x07, 0xcf, 0x30, 0x0d, 0xdb, 0x13, 0xce, 0x04, 0x23, 0x9b, 0x11, 0xf7,
	0x87, 0x7e, 0xea, 0xb7, 0x27, 0xe3, 0x3c, 0x8a, 0xd3, 0xc6, 0x3b, 0x11, 0x63, 0xd1, 0x18, 0x6f,
	0xaa, 0xd5, 0x41, 0x3e, 0xbc, 0x89, 0xc9, 0x44, 0x4c, 0xf5, 0xe6, 0xd6, 0x5f, 0x2e, 0xac, 0xf7,
	0xd4, 0xbe, 0x1d, 0x96, 0x0e, 0xe3, 0x88, 0x6c, 0x82, 0x1b, 0x87, 0x9e, 0xd3, 0x74, 0xb6, 0x4b,
	0xd4, 0x8d, 0x43, 0xb2, 0x05, 0x65, 0xc6, 0xa3, 0x6e, 0xe8, 0xb9, 0xca, 0xa4, 0x15, 0x42, 0x60,
	0x25, 0xf5, 0x13, 0xf4, 0x4a, 0x4d, 0x67, 0xbb, 0x46, 0x95, 0x2c, 0x6d, 0x62, 0x3a, 0x41, 0x6f,
	0x45, 0xdb, 0xa4, 0x4c, 0xea, 0x50, 0xca, 0xf9, 0xd8, 0x2b, 0x2b, 0x93, 0x14, 0x49, 0x03, 0x56,
	0xbf, 0xcd, 0x58, 0xba, 0xeb, 0x0b, 0xdf, 0xab, 0x28, 0x73, 0xa1, 0x93, 0x0c, 0xde, 0x0e, 0x31,
	0xe0, 0xd3, 0x89, 0xc0, 0xb0, 0x8f, 0x41, 0xce, 0xf1, 0xa1, 0xdd, 0x5a, 0x6d, 0x96, 0xb6, 0xd7,
	0x3a, 0x9f, 0xb7, 0xe7, 0xb9, 0xb5, 0x67, 0xa1, 0xb7, 0x77, 0x5f, 0x7d, 0x76, 0x2f, 0x15, 0x7c,
	0x4a, 0x97, 0x79, 0x6e, 0x3c, 0x84, 0x6b, 0xa7, 0x1d, 0x94, 0x14, 0x9e, 0xe1, 0x54, 0x45, 0xa4,
	0x46, 0xa5, 0x28, 0x43, 0xf2, 0xc2, 0x1f, 0xe7, 0xa8, 0x42, 0x52, 0xa3, 0x5a, 0xb9, 0xeb, 0xde,
	0x71, 0x5a, 0x7f, 0xbb, 0xf0, 0x7f, 0x0d, 0xa9, 0x2f, 0x7c, 0x91, 0x67, 0x14, 0x9f, 0xe7, 0x98,
	0x09, 0xf2, 0x29, 0x54, 0x02, 0x85, 0x51, 0xb9, 0x59, 0xeb, 0x5c, 0x3b, 0x8d, 0x07, 0x35, 0x7b,
	0xc9, 0x43, 0xa8, 0x8e, 0xd0, 0x0f, 0x91, 0x67, 0x9e, 0xab, 0xe8, 0xdf, 0x7a, 0xf5, 0xb1, 0xb9,
	0x6f, 0xb5, 0xbf, 0xd4, 0x47, 0x34, 0x6b, 0xeb, 0x80, 0xec, 0x40, 0x79, 0x88, 0x22, 0x18, 0xa9,
	0x8c, 0x6d, 0x76, 0x3e, 0x3e, 0x8f, 0xa7, 0x07, 0xf2, 0x40, 0x37, 0x1d, 0x32, 0xaa, 0xcf, 0x36,
	0xee, 0xc2, 0xfa, 0xac, 0xf7, 0xd7, 0x0a, 0xcd, 0x1d, 0xa8, 0x15, 0xfe, 0x08, 0x40, 0xa5, 0x7f,
	0x74, 0xef, 0xe8, 0x49, 0xbf, 0x7e, 0x89, 0x54, 0xa1, 0x74, 0xaf, 0xd7, 0xad, 0x3b, 0x64, 0x0d,
	0xaa, 0x87, 0x7b, 0x47, 0xb4, 0xbb, 0xd3, 0xaf, 0xbb, 0xa4, 0x06, 0xe5, 0xdd, 0xbd, 0xfb, 0x4f,
	0xf6, 0xeb, 0xa5, 0xd6, 0xaf, 0x0e, 0x6c, 0xcd, 0xc3, 0xcb, 0x26, 0x2c, 0xcd, 0x90, 0x74, 0xa1,
	0x92, 0x29, 0x8b, 0x42, 0xb0, 0xd9, 0xf9, 0xe4, 0x74, 0x52, 0xfa, 0xd4, 0xbc, 0xd1, 0x38, 0x90,
	0xb5, 0x1b, 0xa7, 0x43, 0x66, 0x60, 0x2b, 0xb9, 0xd5, 0xb6, 0x9d, 0xa1, 0xf7, 0x4a, 0x7c, 0x4f,
	0x1e, 0x1d, 0x3c, 0x7a, 0xfc, 0xf5, 0xa3, 0xfa, 0x25, 0x52, 0x01, 0xf7, 0xf1, 0x41, 0xdd, 0x91,
	0x38, 0xf7, 0x28, 0x7d, 0x4c, 0xeb, 0x6e, 0xeb, 0x07, 0xa8, 0x1d, 0xc5, 0x09, 0x52, 0x3f, 0x8d,
	0x90, 0x78, 0x50, 0x1d, 0x72, 0x96, 0x50, 0xff, 0xa5, 0x09, 0x8f, 0x55, 0x65, 0x88, 0x04, 0x93,
	0x76, 0x13, 0x22, 0xa5, 0x90, 0x26, 0xac, 0xc9, 0x0d, 0x7b, 0x13, 0x16, 0x8c, 0x0e, 0xfb, 0x2a,
	0x4b, 0x25, 0x3a, 0x6b, 0x22, 0xd7, 0xa0, 0x26, 0x98, 0x5d, 0x5f, 0x51, 0xeb, 0xc7, 0x86, 0xd6,
	0x6f, 0x0e, 0xd4, 0x64, 0xcd, 0x7e, 0x95, 0x23, 0x57, 0x69, 0xe0, 0x38, 0xec, 0x86, 0xe6, 0xdb,
	0x5a, 0x21, 0x37, 0x60, 0x23, 0xf1, 0xbf, 0x93, 0xbb, 0x7a, 0x2c, 0x4e, 0x45, 0x66, 0x5a, 0x7a,
	0xde, 0x48, 0xae, 0x03, 0xc4, 0xa9, 0x40, 0xfe, 0xc2, 0x1f, 0x17, 0x40, 0x66, 0x2c, 0xe4, 0x33,
	0xa8, 0x09, 0x4b, 0x53, 0xe1, 0x58, 0xeb, 0x5c, 0x5d, 0x0c, 0x7c, 0x11, 0x07, 0x7a, 0xbc, 0x57,
	0xc6, 0x58, 0x76, 0xba, 0x1a, 0x06, 0xeb, 0x54, 0xc9, 0xad, 0x1f, 0x5d, 0xa8, 0x17, 0xb0, 0x2f,
	0xd6, 0x2d, 0xfb, 0x8b, 0xdd, 0x72, 0xa2, 0xc6, 0x17, 0x3f, 0xb4, 0xa4, 0x55, 0x6e, 0x43, 0xf5,
	0x79, 0x8e, 0x3c, 0xc6, 0xcc, 0x2b, 0x29, 0x47, 0x57, 0x97, 0x3b, 0xb2, 0x3b, 0x2f, 0xd4, 0x1a,
	0xbf, 0x3b, 0xf0, 0xbf, 0x19, 0x6c, 0xa6, 0xba, 0xaf, 0x40, 0x65, 0xc8, 0xfd, 0x04, 0x65, 0x75,
	0x97, 0xb6, 0xd7, 0xa9, 0xd1, 0xc8, 0x01, 0xac, 0x26, 0x28, 0xfc, 0x50, 0x4e, 0x45, 0x4d, 0xf4,
	0xe6, 0x29, 0x44, 0x4d, 0xd1, 0x1f, 0x9a, 0x13, 0x9a, 0x6a, 0xe1, 0xa0, 0xf1, 0x05, 0x6c, 0xcc,
	0x2d, 0xbd, 0x16, 0xee, 0x5f, 0x5c, 0xb8, 0x4c, 0x31, 0x63, 0x39, 0x0f, 0xf0, 0x62, 0xb9, 0x7b,
	0xb0, 0x98, 0xbb, 0x8f, 0x16, 0x8f, 0x2d, 0x7c, 0x67, 0x49, 0xea, 0xae, 0x40, 0x25, 0x41, 0x31,
	0x62, 0xa1, 0xb9, 0x98, 0x8c, 0x26, 0x4b, 0x6f, 0xe2, 0x8b, 0x91, 0xbd, 0x9a, 0xa4, 0x2c, 0x6d,
	0x03, 0x16, 0x4e, 0x6d, 0x39, 0x4a, 0xf9, 0x42, 0x59, 0xfc, 0xc3, 0x81, 0xfa, 0x31, 0x4a, 0x93,
	0x44, 0x02, 0x2b, 0x01, 0x0b, 0x51, 0x79, 0x28, 0x53, 0x25, 0x9f, 0xa3, 0x50, 0x17, 0xdd, 0x2c,
	0x61, 0x6b, 0x19, 0x94, 0xde, 0x10, 0x83, 0x7f, 0x1d, 0xa8, 0xf7, 0x05, 0x47, 0x3f, 0x89, 0xd3,
	0xc8, 0x26, 0xb4, 0x01, 0xab, 0x1a, 0x55, 0xd7, 0xbe, 0x0a, 0x0a, 0xfd, 0x1c, 0x4c, 0x16, 0xdd,
	0x2d, 0x61, 0xa2, 0x66, 0xe2, 0x24, 0x0e, 0x4c, 0xda, 0xb4, 0x52, 0xf0, 0x33, 0x59, 0x93, 0xb2,
	0x9c, 0x4e, 0x59, 0x3e, 0xc8, 0x02, 0x1e, 0x0f, 0x30, 0x54, 0xb9, 0x5b, 0xa5, 0x33, 0x96, 0x0b,
	0xf1, 0xff, 0x66, 0x86, 0xfe, 0x21, 0x66, 0x99, 0x1f, 0xe1, 0xa9, 0xf4, 0x0b, 0xd4, 0xee, 0x2c,
	0x6a, 0x0f, 0xaa, 0x89, 0x3e, 0x6c, 0xd8, 0x58, 0xb5, 0xf5, 0x21, 0x6c, 0x16, 0xfe, 0x77, 0xc6,
	0x2c, 0x43, 0xe9, 0x21, 0x60, 0x79, 0x2a, 0x8c, 0x6b, 0xad, 0xb4, 0x7e, 0x76, 0x61, 0x83, 0x62,
	0x1a, 0x22, 0xb7, 0x49, 0x30, 0xcf, 0x28, 0xe7, 0xf8, 0x19, 0xb5, 0x05, 0xe5, 0x97, 0x71, 0x28,
	0x46, 0xea, 0xdb, 0x65, 0xaa, 0x15, 0x59, 0xff, 0x23, 0x8c, 0xa3, 0x91, 0x50, 0x9f, 0x2e, 0x53,
	0xa3, 0x49, 0x4c, 0x72, 0x0e, 0xb3, 0x5c, 0xa8, 0x60, 0x96, 0xa9, 0x55, 0x25, 0x3f, 0x29, 0x7e,
	0xcf, 0x52, 0x34, 0xaf, 0xb4, 0x42, 0x97, 0x6b, 0x98, 0x06, 0x2c, 0x8c, 0xd3, 0xc8, 0x3e, 0xd5,
	0xac, 0x2e, 0xd7, 0x86, 0xf1, 0x18, 0x7b, 0xb2, 0xab, 0xaa, 0x7a, 0xcd, 0xea, 0xf2, 0xa6, 0xe2,
	0x0a, 0xfe, 0x01, 0x4e, 0xbd, 0x55, 0xb5, 0x78, 0x6c, 0x90, 0x18, 0x43, 0x96, 0xf8, 0x71, 0xea,
	0xd5, 0x74, 0x8f, 0x6a, 0x4d, 0x32, 0x0a, 0x71, 0x90, 0x47, 0x1e, 0xa8, 0xa4, 0x6a, 0x45, 0xc6,
	0xcc, 0x86, 0xc2, 0xb4, 0xd4, 0x16, 0x94, 0x91, 0x73, 0xc6, 0xed, 0xdd, 0xa6, 0x94, 0xce, 0x4f,
	0x2e, 0x6c, 0xdc, 0xd7, 0xcf, 0x60, 0x3d, 0x61, 0x08, 0x85, 0xf2, 0xce, 0x08, 0x83, 0x67, 0xe4,
	0x83, 0x73, 0xbc, 0x75, 0x1a, 0x37, 0xce, 0xf3, 0x76, 0x20, 0x87, 0xb0, 0x6a, 0x7b, 0x93, 0xbc,
	0x77, 0xc6, 0x88, 0x6a, 0x34, 0xcf, 0x6a, 0x6b, 0xd2, 0x9b, 0xbd, 0xb3, 0x9b, 0x67, 0x5d, 0x57,
	0x8d, 0xf7, 0xcf, 0x9c, 0xf3, 0x9d, 0x3f, 0x1d, 0xb8, 0xbc, 0xaf, 0x37, 0xf5, 0xc6, 0xbe, 0x18,
	0x32, 0x9e, 0x90, 0xa7, 0xf0, 0x96, 0x95, 0x35, 0x29, 0x5b, 0x55, 0x6f, 0x80, 0xc1, 0x53, 0xf9,
	0xde, 0x9d, 0xf5, 0xfd, 0x06, 0xb9, 0xfc, 0xe3, 0xc0, 0xe5, 0xa2, 0x5f, 0x4c, 0x52, 0x0f, 0xa0,
	0xba, 0xc3, 0xd2, 0x14, 0x03, 0x41, 0x4e, 0xbd, 0x59, 0x4e, 0x42, 0x5f, 0xec, 0xec, 0x5b, 0x0e,
	0x39, 0x84, 0x6a, 0x8f, 0xb3, 0x00, 0xb3, 0x8c, 0x34, 0xcf, 0x1a, 0x5c, 0x67, 0x3b, 0x24, 0xbb,
	0x00, 0xbb, 0x71, 0x16, 0x18, 0x78, 0x57, 0xda, 0xfa, 0xb7, 0xab, 0x6d, 0x7f, 0xbb, 0xda, 0x7b,
	0xf2, 0xb7, 0xab, 0x71, 0x7d, 0xa9, 0x1f, 0x35, 0x12, 0x3a, 0x7d, 0x59, 0x62, 0xb2, 0xe0, 0x91,
	0x93, 0x7d, 0xa8, 0x68, 0x99, 0xbc, 0x7b, 0x32, 0x13, 0x33, 0xf3, 0xe1, 0xa4, 0xd3, 0xf9, 0x9e,
	0x19, 0x54, 0x14, 0x88, 0xdb, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x93, 0xe7, 0xc7, 0x05, 0x2a,
	0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackendPluginClient is the client API for BackendPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackendPluginClient interface {
	// Get the plugin status
	Check(ctx context.Context, in *PluginStatusRequest, opts ...grpc.CallOption) (*PluginStatusResponse, error)
	// HTTP Style request
	Resource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	// Well typed query interface
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
}

type backendPluginClient struct {
	cc *grpc.ClientConn
}

func NewBackendPluginClient(cc *grpc.ClientConn) BackendPluginClient {
	return &backendPluginClient{cc}
}

func (c *backendPluginClient) Check(ctx context.Context, in *PluginStatusRequest, opts ...grpc.CallOption) (*PluginStatusResponse, error) {
	out := new(PluginStatusResponse)
	err := c.cc.Invoke(ctx, "/grafana.plugin.BackendPlugin/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Resource(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, "/grafana.plugin.BackendPlugin/Resource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, "/grafana.plugin.BackendPlugin/DataQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendPluginServer is the server API for BackendPlugin service.
type BackendPluginServer interface {
	// Get the plugin status
	Check(context.Context, *PluginStatusRequest) (*PluginStatusResponse, error)
	// HTTP Style request
	Resource(context.Context, *ResourceRequest) (*ResourceResponse, error)
	// Well typed query interface
	DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
}

// UnimplementedBackendPluginServer can be embedded to have forward compatible implementations.
type UnimplementedBackendPluginServer struct {
}

func (*UnimplementedBackendPluginServer) Check(ctx context.Context, req *PluginStatusRequest) (*PluginStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedBackendPluginServer) Resource(ctx context.Context, req *ResourceRequest) (*ResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resource not implemented")
}
func (*UnimplementedBackendPluginServer) DataQuery(ctx context.Context, req *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataQuery not implemented")
}

func RegisterBackendPluginServer(s *grpc.Server, srv BackendPluginServer) {
	s.RegisterService(&_BackendPlugin_serviceDesc, srv)
}

func _BackendPlugin_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.BackendPlugin/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Check(ctx, req.(*PluginStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Resource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Resource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.BackendPlugin/Resource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Resource(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_DataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).DataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.BackendPlugin/DataQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).DataQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackendPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.BackendPlugin",
	HandlerType: (*BackendPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _BackendPlugin_Check_Handler,
		},
		{
			MethodName: "Resource",
			Handler:    _BackendPlugin_Resource_Handler,
		},
		{
			MethodName: "DataQuery",
			Handler:    _BackendPlugin_DataQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

// GrafanaPlatformClient is the client API for GrafanaPlatform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrafanaPlatformClient interface {
	PlatformPluginRequest(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	PlatformPluginQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
}

type grafanaPlatformClient struct {
	cc *grpc.ClientConn
}

func NewGrafanaPlatformClient(cc *grpc.ClientConn) GrafanaPlatformClient {
	return &grafanaPlatformClient{cc}
}

func (c *grafanaPlatformClient) PlatformPluginRequest(ctx context.Context, in *ResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, "/grafana.plugin.GrafanaPlatform/PlatformPluginRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grafanaPlatformClient) PlatformPluginQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, "/grafana.plugin.GrafanaPlatform/PlatformPluginQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrafanaPlatformServer is the server API for GrafanaPlatform service.
type GrafanaPlatformServer interface {
	PlatformPluginRequest(context.Context, *ResourceRequest) (*ResourceResponse, error)
	PlatformPluginQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
}

// UnimplementedGrafanaPlatformServer can be embedded to have forward compatible implementations.
type UnimplementedGrafanaPlatformServer struct {
}

func (*UnimplementedGrafanaPlatformServer) PlatformPluginRequest(ctx context.Context, req *ResourceRequest) (*ResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlatformPluginRequest not implemented")
}
func (*UnimplementedGrafanaPlatformServer) PlatformPluginQuery(ctx context.Context, req *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlatformPluginQuery not implemented")
}

func RegisterGrafanaPlatformServer(s *grpc.Server, srv GrafanaPlatformServer) {
	s.RegisterService(&_GrafanaPlatform_serviceDesc, srv)
}

func _GrafanaPlatform_PlatformPluginRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrafanaPlatformServer).PlatformPluginRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.GrafanaPlatform/PlatformPluginRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrafanaPlatformServer).PlatformPluginRequest(ctx, req.(*ResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrafanaPlatform_PlatformPluginQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrafanaPlatformServer).PlatformPluginQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.GrafanaPlatform/PlatformPluginQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrafanaPlatformServer).PlatformPluginQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrafanaPlatform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.GrafanaPlatform",
	HandlerType: (*GrafanaPlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlatformPluginRequest",
			Handler:    _GrafanaPlatform_PlatformPluginRequest_Handler,
		},
		{
			MethodName: "PlatformPluginQuery",
			Handler:    _GrafanaPlatform_PlatformPluginQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

// StreamingPluginClient is the client API for StreamingPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamingPluginClient interface {
	// Called by grafana before the first request
	// Grafana server will set up a websocket that will broadcast to all listeners
	Connect(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (StreamingPlugin_ConnectClient, error)
	// If the message is not empty, send that to the user
	// throwing an error will make sure the user is not subscribed
	Process(ctx context.Context, in *StreamingRequest, opts ...grpc.CallOption) (*StreamingMessage, error)
	// Stop streaming to that instance, returns the number of open connections
	Disconnect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StreamingClose, error)
}

type streamingPluginClient struct {
	cc *grpc.ClientConn
}

func NewStreamingPluginClient(cc *grpc.ClientConn) StreamingPluginClient {
	return &streamingPluginClient{cc}
}

func (c *streamingPluginClient) Connect(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (StreamingPlugin_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamingPlugin_serviceDesc.Streams[0], "/grafana.plugin.StreamingPlugin/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingPluginConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamingPlugin_ConnectClient interface {
	Recv() (*StreamingMessage, error)
	grpc.ClientStream
}

type streamingPluginConnectClient struct {
	grpc.ClientStream
}

func (x *streamingPluginConnectClient) Recv() (*StreamingMessage, error) {
	m := new(StreamingMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamingPluginClient) Process(ctx context.Context, in *StreamingRequest, opts ...grpc.CallOption) (*StreamingMessage, error) {
	out := new(StreamingMessage)
	err := c.cc.Invoke(ctx, "/grafana.plugin.StreamingPlugin/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamingPluginClient) Disconnect(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StreamingClose, error) {
	out := new(StreamingClose)
	err := c.cc.Invoke(ctx, "/grafana.plugin.StreamingPlugin/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamingPluginServer is the server API for StreamingPlugin service.
type StreamingPluginServer interface {
	// Called by grafana before the first request
	// Grafana server will set up a websocket that will broadcast to all listeners
	Connect(*PluginConfig, StreamingPlugin_ConnectServer) error
	// If the message is not empty, send that to the user
	// throwing an error will make sure the user is not subscribed
	Process(context.Context, *StreamingRequest) (*StreamingMessage, error)
	// Stop streaming to that instance, returns the number of open connections
	Disconnect(context.Context, *empty.Empty) (*StreamingClose, error)
}

// UnimplementedStreamingPluginServer can be embedded to have forward compatible implementations.
type UnimplementedStreamingPluginServer struct {
}

func (*UnimplementedStreamingPluginServer) Connect(req *PluginConfig, srv StreamingPlugin_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedStreamingPluginServer) Process(ctx context.Context, req *StreamingRequest) (*StreamingMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (*UnimplementedStreamingPluginServer) Disconnect(ctx context.Context, req *empty.Empty) (*StreamingClose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}

func RegisterStreamingPluginServer(s *grpc.Server, srv StreamingPluginServer) {
	s.RegisterService(&_StreamingPlugin_serviceDesc, srv)
}

func _StreamingPlugin_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PluginConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamingPluginServer).Connect(m, &streamingPluginConnectServer{stream})
}

type StreamingPlugin_ConnectServer interface {
	Send(*StreamingMessage) error
	grpc.ServerStream
}

type streamingPluginConnectServer struct {
	grpc.ServerStream
}

func (x *streamingPluginConnectServer) Send(m *StreamingMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _StreamingPlugin_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingPluginServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.StreamingPlugin/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingPluginServer).Process(ctx, req.(*StreamingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamingPlugin_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamingPluginServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.StreamingPlugin/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamingPluginServer).Disconnect(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamingPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.StreamingPlugin",
	HandlerType: (*StreamingPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _StreamingPlugin_Process_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _StreamingPlugin_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _StreamingPlugin_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend.proto",
}

// RendererClient is the client API for Renderer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RendererClient interface {
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type rendererClient struct {
	cc *grpc.ClientConn
}

func NewRendererClient(cc *grpc.ClientConn) RendererClient {
	return &rendererClient{cc}
}

func (c *rendererClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, "/grafana.plugin.Renderer/Render", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RendererServer is the server API for Renderer service.
type RendererServer interface {
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
}

// UnimplementedRendererServer can be embedded to have forward compatible implementations.
type UnimplementedRendererServer struct {
}

func (*UnimplementedRendererServer) Render(ctx context.Context, req *RenderRequest) (*RenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Render not implemented")
}

func RegisterRendererServer(s *grpc.Server, srv RendererServer) {
	s.RegisterService(&_Renderer_serviceDesc, srv)
}

func _Renderer_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendererServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grafana.plugin.Renderer/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendererServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Renderer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grafana.plugin.Renderer",
	HandlerType: (*RendererServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _Renderer_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
