edition = "2024";

package grafana.plugin.v3;

import "grafana/plugin/v3/common.proto";

// RouteService enables HTTP-style requests over gRPC.
// It mirrors the pluginv2 Resource service, but the request does not carry a
// PluginContext.
service RouteService {
  // CallRoute issues an HTTP-style request and streams the response back.
  rpc CallRoute(CallRouteRequest) returns (stream CallRouteResponse);
}

// RouteResource is the resource object referenced by the requested path
message RouteResource {
  // The resource api version
  GroupVersion api_version = 1;

  // the parent resource type (eg, dashboards)
  string resource = 2;

  // tenant identifier
  string namespace = 3;

  // The resource name when attached to a resource (ie, the route is a "subresource")
  string name = 4;

  // the resource version -- changes here indicate that raw body has changed
  string rv = 5;

  // JSON raw resource (when)
  bytes raw = 6;
}

// CallRouteRequest is the request for RouteService.CallRoute.
message CallRouteRequest {
  // Depending where the route is mounted, the parent resource will be populated
  RouteResource parent = 1;

  // path is the request path.
  string path = 2;

  // method is the HTTP method.
  string method = 3;

  // url is the request URL.
  string url = 4;

  // headers are the raw HTTP request headers.
  map<string, StringList> headers = 5;

  // body is the raw HTTP request body.
  bytes body = 6;
}

// CallRouteResponse is a streamed chunk of the response for RouteService.CallRoute.
// The code and headers will only be used for the first stream chunk.
message CallRouteResponse {
  // code maps to raw HTTP status codes when passed over HTTP.
  int32 code = 1;

  // headers are the raw HTTP headers sent to the client.
  map<string, StringList> headers = 2;

  // body are the raw HTTP body bytes sent to the client.
  bytes body = 3;
}
