// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package pluginv2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckHealth_Response_HealthStatus int32

const (
	CheckHealth_Response_UNKNOWN CheckHealth_Response_HealthStatus = 0
	CheckHealth_Response_OK      CheckHealth_Response_HealthStatus = 1
	CheckHealth_Response_ERROR   CheckHealth_Response_HealthStatus = 2
)

var CheckHealth_Response_HealthStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "OK",
	2: "ERROR",
}

var CheckHealth_Response_HealthStatus_value = map[string]int32{
	"UNKNOWN": 0,
	"OK":      1,
	"ERROR":   2,
}

func (x CheckHealth_Response_HealthStatus) String() string {
	return proto.EnumName(CheckHealth_Response_HealthStatus_name, int32(x))
}

func (CheckHealth_Response_HealthStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9, 1, 0}
}

type DataSourceConfig struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Database             string   `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	BasicAuthEnabled     bool     `protobuf:"varint,6,opt,name=basicAuthEnabled,proto3" json:"basicAuthEnabled,omitempty"`
	BasicAuthUser        string   `protobuf:"bytes,7,opt,name=basicAuthUser,proto3" json:"basicAuthUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataSourceConfig) Reset()         { *m = DataSourceConfig{} }
func (m *DataSourceConfig) String() string { return proto.CompactTextString(m) }
func (*DataSourceConfig) ProtoMessage()    {}
func (*DataSourceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{0}
}

func (m *DataSourceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataSourceConfig.Unmarshal(m, b)
}
func (m *DataSourceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataSourceConfig.Marshal(b, m, deterministic)
}
func (m *DataSourceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataSourceConfig.Merge(m, src)
}
func (m *DataSourceConfig) XXX_Size() int {
	return xxx_messageInfo_DataSourceConfig.Size(m)
}
func (m *DataSourceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DataSourceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DataSourceConfig proto.InternalMessageInfo

func (m *DataSourceConfig) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataSourceConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataSourceConfig) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DataSourceConfig) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *DataSourceConfig) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DataSourceConfig) GetBasicAuthEnabled() bool {
	if m != nil {
		return m.BasicAuthEnabled
	}
	return false
}

func (m *DataSourceConfig) GetBasicAuthUser() string {
	if m != nil {
		return m.BasicAuthUser
	}
	return ""
}

type PluginConfig struct {
	OrgId                   int64             `protobuf:"varint,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	PluginId                string            `protobuf:"bytes,2,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	PluginType              string            `protobuf:"bytes,3,opt,name=pluginType,proto3" json:"pluginType,omitempty"`
	JsonData                []byte            `protobuf:"bytes,4,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	DecryptedSecureJsonData map[string]string `protobuf:"bytes,5,rep,name=decryptedSecureJsonData,proto3" json:"decryptedSecureJsonData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UpdatedMS               int64             `protobuf:"varint,6,opt,name=updatedMS,proto3" json:"updatedMS,omitempty"`
	DatasourceConfig        *DataSourceConfig `protobuf:"bytes,7,opt,name=datasourceConfig,proto3" json:"datasourceConfig,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}          `json:"-"`
	XXX_unrecognized        []byte            `json:"-"`
	XXX_sizecache           int32             `json:"-"`
}

func (m *PluginConfig) Reset()         { *m = PluginConfig{} }
func (m *PluginConfig) String() string { return proto.CompactTextString(m) }
func (*PluginConfig) ProtoMessage()    {}
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{1}
}

func (m *PluginConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfig.Unmarshal(m, b)
}
func (m *PluginConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfig.Marshal(b, m, deterministic)
}
func (m *PluginConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfig.Merge(m, src)
}
func (m *PluginConfig) XXX_Size() int {
	return xxx_messageInfo_PluginConfig.Size(m)
}
func (m *PluginConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfig proto.InternalMessageInfo

func (m *PluginConfig) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *PluginConfig) GetPluginId() string {
	if m != nil {
		return m.PluginId
	}
	return ""
}

func (m *PluginConfig) GetPluginType() string {
	if m != nil {
		return m.PluginType
	}
	return ""
}

func (m *PluginConfig) GetJsonData() []byte {
	if m != nil {
		return m.JsonData
	}
	return nil
}

func (m *PluginConfig) GetDecryptedSecureJsonData() map[string]string {
	if m != nil {
		return m.DecryptedSecureJsonData
	}
	return nil
}

func (m *PluginConfig) GetUpdatedMS() int64 {
	if m != nil {
		return m.UpdatedMS
	}
	return 0
}

func (m *PluginConfig) GetDatasourceConfig() *DataSourceConfig {
	if m != nil {
		return m.DatasourceConfig
	}
	return nil
}

type User struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type TimeRange struct {
	FromEpochMS          int64    `protobuf:"varint,1,opt,name=fromEpochMS,proto3" json:"fromEpochMS,omitempty"`
	ToEpochMS            int64    `protobuf:"varint,2,opt,name=toEpochMS,proto3" json:"toEpochMS,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRange) Reset()         { *m = TimeRange{} }
func (m *TimeRange) String() string { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()    {}
func (*TimeRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{3}
}

func (m *TimeRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRange.Unmarshal(m, b)
}
func (m *TimeRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRange.Marshal(b, m, deterministic)
}
func (m *TimeRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRange.Merge(m, src)
}
func (m *TimeRange) XXX_Size() int {
	return xxx_messageInfo_TimeRange.Size(m)
}
func (m *TimeRange) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRange.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRange proto.InternalMessageInfo

func (m *TimeRange) GetFromEpochMS() int64 {
	if m != nil {
		return m.FromEpochMS
	}
	return 0
}

func (m *TimeRange) GetToEpochMS() int64 {
	if m != nil {
		return m.ToEpochMS
	}
	return 0
}

type DataQuery struct {
	RefId                string     `protobuf:"bytes,1,opt,name=refId,proto3" json:"refId,omitempty"`
	MaxDataPoints        int64      `protobuf:"varint,2,opt,name=maxDataPoints,proto3" json:"maxDataPoints,omitempty"`
	IntervalMS           int64      `protobuf:"varint,3,opt,name=intervalMS,proto3" json:"intervalMS,omitempty"`
	TimeRange            *TimeRange `protobuf:"bytes,4,opt,name=timeRange,proto3" json:"timeRange,omitempty"`
	Json                 []byte     `protobuf:"bytes,5,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DataQuery) Reset()         { *m = DataQuery{} }
func (m *DataQuery) String() string { return proto.CompactTextString(m) }
func (*DataQuery) ProtoMessage()    {}
func (*DataQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{4}
}

func (m *DataQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQuery.Unmarshal(m, b)
}
func (m *DataQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQuery.Marshal(b, m, deterministic)
}
func (m *DataQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQuery.Merge(m, src)
}
func (m *DataQuery) XXX_Size() int {
	return xxx_messageInfo_DataQuery.Size(m)
}
func (m *DataQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQuery.DiscardUnknown(m)
}

var xxx_messageInfo_DataQuery proto.InternalMessageInfo

func (m *DataQuery) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *DataQuery) GetMaxDataPoints() int64 {
	if m != nil {
		return m.MaxDataPoints
	}
	return 0
}

func (m *DataQuery) GetIntervalMS() int64 {
	if m != nil {
		return m.IntervalMS
	}
	return 0
}

func (m *DataQuery) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *DataQuery) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

type DataQueryRequest struct {
	// Plugin Configuration
	Config *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Environment info
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// List of queries
	Queries []*DataQuery `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	//Info about the user who calls the plugin.
	User                 *User    `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataQueryRequest) Reset()         { *m = DataQueryRequest{} }
func (m *DataQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DataQueryRequest) ProtoMessage()    {}
func (*DataQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{5}
}

func (m *DataQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryRequest.Unmarshal(m, b)
}
func (m *DataQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryRequest.Marshal(b, m, deterministic)
}
func (m *DataQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryRequest.Merge(m, src)
}
func (m *DataQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DataQueryRequest.Size(m)
}
func (m *DataQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryRequest proto.InternalMessageInfo

func (m *DataQueryRequest) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *DataQueryRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *DataQueryRequest) GetQueries() []*DataQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *DataQueryRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DataQueryResponse struct {
	// Arrow encoded DataFrames
	// Each frame encodes its own: Errors, meta, and refId
	Frames [][]byte `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	// Additional response metadata
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataQueryResponse) Reset()         { *m = DataQueryResponse{} }
func (m *DataQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DataQueryResponse) ProtoMessage()    {}
func (*DataQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{6}
}

func (m *DataQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryResponse.Unmarshal(m, b)
}
func (m *DataQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryResponse.Marshal(b, m, deterministic)
}
func (m *DataQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryResponse.Merge(m, src)
}
func (m *DataQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DataQueryResponse.Size(m)
}
func (m *DataQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryResponse proto.InternalMessageInfo

func (m *DataQueryResponse) GetFrames() [][]byte {
	if m != nil {
		return m.Frames
	}
	return nil
}

func (m *DataQueryResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CallResource struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResource) Reset()         { *m = CallResource{} }
func (m *CallResource) String() string { return proto.CompactTextString(m) }
func (*CallResource) ProtoMessage()    {}
func (*CallResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7}
}

func (m *CallResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResource.Unmarshal(m, b)
}
func (m *CallResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResource.Marshal(b, m, deterministic)
}
func (m *CallResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResource.Merge(m, src)
}
func (m *CallResource) XXX_Size() int {
	return xxx_messageInfo_CallResource.Size(m)
}
func (m *CallResource) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResource.DiscardUnknown(m)
}

var xxx_messageInfo_CallResource proto.InternalMessageInfo

type CallResource_StringList struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallResource_StringList) Reset()         { *m = CallResource_StringList{} }
func (m *CallResource_StringList) String() string { return proto.CompactTextString(m) }
func (*CallResource_StringList) ProtoMessage()    {}
func (*CallResource_StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7, 0}
}

func (m *CallResource_StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResource_StringList.Unmarshal(m, b)
}
func (m *CallResource_StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResource_StringList.Marshal(b, m, deterministic)
}
func (m *CallResource_StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResource_StringList.Merge(m, src)
}
func (m *CallResource_StringList) XXX_Size() int {
	return xxx_messageInfo_CallResource_StringList.Size(m)
}
func (m *CallResource_StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResource_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_CallResource_StringList proto.InternalMessageInfo

func (m *CallResource_StringList) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type CallResource_Request struct {
	Config               *PluginConfig                       `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Path                 string                              `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               string                              `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string                              `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Headers              map[string]*CallResource_StringList `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte                              `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	User                 *User                               `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *CallResource_Request) Reset()         { *m = CallResource_Request{} }
func (m *CallResource_Request) String() string { return proto.CompactTextString(m) }
func (*CallResource_Request) ProtoMessage()    {}
func (*CallResource_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7, 1}
}

func (m *CallResource_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResource_Request.Unmarshal(m, b)
}
func (m *CallResource_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResource_Request.Marshal(b, m, deterministic)
}
func (m *CallResource_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResource_Request.Merge(m, src)
}
func (m *CallResource_Request) XXX_Size() int {
	return xxx_messageInfo_CallResource_Request.Size(m)
}
func (m *CallResource_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResource_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CallResource_Request proto.InternalMessageInfo

func (m *CallResource_Request) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *CallResource_Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CallResource_Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallResource_Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CallResource_Request) GetHeaders() map[string]*CallResource_StringList {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *CallResource_Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *CallResource_Request) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CallResource_Response struct {
	Code                 int32                               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Headers              map[string]*CallResource_StringList `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte                              `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *CallResource_Response) Reset()         { *m = CallResource_Response{} }
func (m *CallResource_Response) String() string { return proto.CompactTextString(m) }
func (*CallResource_Response) ProtoMessage()    {}
func (*CallResource_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{7, 2}
}

func (m *CallResource_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallResource_Response.Unmarshal(m, b)
}
func (m *CallResource_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallResource_Response.Marshal(b, m, deterministic)
}
func (m *CallResource_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallResource_Response.Merge(m, src)
}
func (m *CallResource_Response) XXX_Size() int {
	return xxx_messageInfo_CallResource_Response.Size(m)
}
func (m *CallResource_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CallResource_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CallResource_Response proto.InternalMessageInfo

func (m *CallResource_Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CallResource_Response) GetHeaders() map[string]*CallResource_StringList {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *CallResource_Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type CollectMetrics struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectMetrics) Reset()         { *m = CollectMetrics{} }
func (m *CollectMetrics) String() string { return proto.CompactTextString(m) }
func (*CollectMetrics) ProtoMessage()    {}
func (*CollectMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8}
}

func (m *CollectMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectMetrics.Unmarshal(m, b)
}
func (m *CollectMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectMetrics.Marshal(b, m, deterministic)
}
func (m *CollectMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectMetrics.Merge(m, src)
}
func (m *CollectMetrics) XXX_Size() int {
	return xxx_messageInfo_CollectMetrics.Size(m)
}
func (m *CollectMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_CollectMetrics proto.InternalMessageInfo

type CollectMetrics_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectMetrics_Request) Reset()         { *m = CollectMetrics_Request{} }
func (m *CollectMetrics_Request) String() string { return proto.CompactTextString(m) }
func (*CollectMetrics_Request) ProtoMessage()    {}
func (*CollectMetrics_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8, 0}
}

func (m *CollectMetrics_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectMetrics_Request.Unmarshal(m, b)
}
func (m *CollectMetrics_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectMetrics_Request.Marshal(b, m, deterministic)
}
func (m *CollectMetrics_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectMetrics_Request.Merge(m, src)
}
func (m *CollectMetrics_Request) XXX_Size() int {
	return xxx_messageInfo_CollectMetrics_Request.Size(m)
}
func (m *CollectMetrics_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectMetrics_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CollectMetrics_Request proto.InternalMessageInfo

type CollectMetrics_Payload struct {
	Prometheus           []byte   `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectMetrics_Payload) Reset()         { *m = CollectMetrics_Payload{} }
func (m *CollectMetrics_Payload) String() string { return proto.CompactTextString(m) }
func (*CollectMetrics_Payload) ProtoMessage()    {}
func (*CollectMetrics_Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8, 1}
}

func (m *CollectMetrics_Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectMetrics_Payload.Unmarshal(m, b)
}
func (m *CollectMetrics_Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectMetrics_Payload.Marshal(b, m, deterministic)
}
func (m *CollectMetrics_Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectMetrics_Payload.Merge(m, src)
}
func (m *CollectMetrics_Payload) XXX_Size() int {
	return xxx_messageInfo_CollectMetrics_Payload.Size(m)
}
func (m *CollectMetrics_Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectMetrics_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_CollectMetrics_Payload proto.InternalMessageInfo

func (m *CollectMetrics_Payload) GetPrometheus() []byte {
	if m != nil {
		return m.Prometheus
	}
	return nil
}

type CollectMetrics_Response struct {
	Metrics              *CollectMetrics_Payload `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CollectMetrics_Response) Reset()         { *m = CollectMetrics_Response{} }
func (m *CollectMetrics_Response) String() string { return proto.CompactTextString(m) }
func (*CollectMetrics_Response) ProtoMessage()    {}
func (*CollectMetrics_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{8, 2}
}

func (m *CollectMetrics_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectMetrics_Response.Unmarshal(m, b)
}
func (m *CollectMetrics_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectMetrics_Response.Marshal(b, m, deterministic)
}
func (m *CollectMetrics_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectMetrics_Response.Merge(m, src)
}
func (m *CollectMetrics_Response) XXX_Size() int {
	return xxx_messageInfo_CollectMetrics_Response.Size(m)
}
func (m *CollectMetrics_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectMetrics_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CollectMetrics_Response proto.InternalMessageInfo

func (m *CollectMetrics_Response) GetMetrics() *CollectMetrics_Payload {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type CheckHealth struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckHealth) Reset()         { *m = CheckHealth{} }
func (m *CheckHealth) String() string { return proto.CompactTextString(m) }
func (*CheckHealth) ProtoMessage()    {}
func (*CheckHealth) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9}
}

func (m *CheckHealth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealth.Unmarshal(m, b)
}
func (m *CheckHealth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealth.Marshal(b, m, deterministic)
}
func (m *CheckHealth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealth.Merge(m, src)
}
func (m *CheckHealth) XXX_Size() int {
	return xxx_messageInfo_CheckHealth.Size(m)
}
func (m *CheckHealth) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealth.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealth proto.InternalMessageInfo

type CheckHealth_Request struct {
	Config               *PluginConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckHealth_Request) Reset()         { *m = CheckHealth_Request{} }
func (m *CheckHealth_Request) String() string { return proto.CompactTextString(m) }
func (*CheckHealth_Request) ProtoMessage()    {}
func (*CheckHealth_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9, 0}
}

func (m *CheckHealth_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealth_Request.Unmarshal(m, b)
}
func (m *CheckHealth_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealth_Request.Marshal(b, m, deterministic)
}
func (m *CheckHealth_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealth_Request.Merge(m, src)
}
func (m *CheckHealth_Request) XXX_Size() int {
	return xxx_messageInfo_CheckHealth_Request.Size(m)
}
func (m *CheckHealth_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealth_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealth_Request proto.InternalMessageInfo

func (m *CheckHealth_Request) GetConfig() *PluginConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type CheckHealth_Response struct {
	Status               CheckHealth_Response_HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pluginv2.CheckHealth_Response_HealthStatus" json:"status,omitempty"`
	Message              string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JsonDetails          string                            `protobuf:"bytes,3,opt,name=jsonDetails,proto3" json:"jsonDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CheckHealth_Response) Reset()         { *m = CheckHealth_Response{} }
func (m *CheckHealth_Response) String() string { return proto.CompactTextString(m) }
func (*CheckHealth_Response) ProtoMessage()    {}
func (*CheckHealth_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab9ba5b8d8b2ba5, []int{9, 1}
}

func (m *CheckHealth_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckHealth_Response.Unmarshal(m, b)
}
func (m *CheckHealth_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckHealth_Response.Marshal(b, m, deterministic)
}
func (m *CheckHealth_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckHealth_Response.Merge(m, src)
}
func (m *CheckHealth_Response) XXX_Size() int {
	return xxx_messageInfo_CheckHealth_Response.Size(m)
}
func (m *CheckHealth_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckHealth_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CheckHealth_Response proto.InternalMessageInfo

func (m *CheckHealth_Response) GetStatus() CheckHealth_Response_HealthStatus {
	if m != nil {
		return m.Status
	}
	return CheckHealth_Response_UNKNOWN
}

func (m *CheckHealth_Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CheckHealth_Response) GetJsonDetails() string {
	if m != nil {
		return m.JsonDetails
	}
	return ""
}

func init() {
	proto.RegisterEnum("pluginv2.CheckHealth_Response_HealthStatus", CheckHealth_Response_HealthStatus_name, CheckHealth_Response_HealthStatus_value)
	proto.RegisterType((*DataSourceConfig)(nil), "pluginv2.DataSourceConfig")
	proto.RegisterType((*PluginConfig)(nil), "pluginv2.PluginConfig")
	proto.RegisterMapType((map[string]string)(nil), "pluginv2.PluginConfig.DecryptedSecureJsonDataEntry")
	proto.RegisterType((*User)(nil), "pluginv2.User")
	proto.RegisterType((*TimeRange)(nil), "pluginv2.TimeRange")
	proto.RegisterType((*DataQuery)(nil), "pluginv2.DataQuery")
	proto.RegisterType((*DataQueryRequest)(nil), "pluginv2.DataQueryRequest")
	proto.RegisterMapType((map[string]string)(nil), "pluginv2.DataQueryRequest.HeadersEntry")
	proto.RegisterType((*DataQueryResponse)(nil), "pluginv2.DataQueryResponse")
	proto.RegisterMapType((map[string]string)(nil), "pluginv2.DataQueryResponse.MetadataEntry")
	proto.RegisterType((*CallResource)(nil), "pluginv2.CallResource")
	proto.RegisterType((*CallResource_StringList)(nil), "pluginv2.CallResource.StringList")
	proto.RegisterType((*CallResource_Request)(nil), "pluginv2.CallResource.Request")
	proto.RegisterMapType((map[string]*CallResource_StringList)(nil), "pluginv2.CallResource.Request.HeadersEntry")
	proto.RegisterType((*CallResource_Response)(nil), "pluginv2.CallResource.Response")
	proto.RegisterMapType((map[string]*CallResource_StringList)(nil), "pluginv2.CallResource.Response.HeadersEntry")
	proto.RegisterType((*CollectMetrics)(nil), "pluginv2.CollectMetrics")
	proto.RegisterType((*CollectMetrics_Request)(nil), "pluginv2.CollectMetrics.Request")
	proto.RegisterType((*CollectMetrics_Payload)(nil), "pluginv2.CollectMetrics.Payload")
	proto.RegisterType((*CollectMetrics_Response)(nil), "pluginv2.CollectMetrics.Response")
	proto.RegisterType((*CheckHealth)(nil), "pluginv2.CheckHealth")
	proto.RegisterType((*CheckHealth_Request)(nil), "pluginv2.CheckHealth.Request")
	proto.RegisterType((*CheckHealth_Response)(nil), "pluginv2.CheckHealth.Response")
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor_5ab9ba5b8d8b2ba5) }

var fileDescriptor_5ab9ba5b8d8b2ba5 = []byte{
	// 1108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0x66, 0xfc, 0xbb, 0x2e, 0x3b, 0x2b, 0xa7, 0x13, 0x05, 0x6b, 0x12, 0x82, 0x63, 0x45, 0x62,
	0xc3, 0xcf, 0x04, 0x9c, 0x03, 0xb0, 0x39, 0x25, 0x5e, 0xaf, 0x92, 0x6c, 0xf6, 0xaf, 0xbd, 0x2b,
	0x44, 0x24, 0x0e, 0xed, 0x99, 0xb6, 0x3d, 0xec, 0xcc, 0xb4, 0xd3, 0xd3, 0xb3, 0xc2, 0x2f, 0xc0,
	0x91, 0x13, 0x57, 0xc4, 0x1b, 0x80, 0xc4, 0x95, 0x37, 0xe0, 0xce, 0x81, 0x37, 0xe0, 0x31, 0x50,
	0xff, 0xcc, 0x8f, 0x37, 0x6b, 0x47, 0x89, 0xc2, 0xad, 0xaa, 0x5c, 0x55, 0x5d, 0x5f, 0xd5, 0x57,
	0x35, 0x86, 0x2b, 0x63, 0xe2, 0x9e, 0xd1, 0xc8, 0x73, 0xe6, 0x9c, 0x09, 0x86, 0x36, 0xe6, 0x41,
	0x32, 0xf5, 0xa3, 0xf3, 0xbe, 0x7d, 0x73, 0xca, 0xd8, 0x34, 0xa0, 0xf7, 0x95, 0x7d, 0x9c, 0x4c,
	0xee, 0xd3, 0x70, 0x2e, 0x16, 0xda, 0xad, 0xf7, 0x97, 0x05, 0xed, 0x1d, 0x22, 0xc8, 0x88, 0x25,
	0xdc, 0xa5, 0x03, 0x16, 0x4d, 0xfc, 0x29, 0xda, 0x84, 0x92, 0xef, 0x75, 0xac, 0xae, 0xb5, 0x55,
	0xc6, 0x25, 0xdf, 0x43, 0x08, 0x2a, 0x11, 0x09, 0x69, 0xa7, 0xd4, 0xb5, 0xb6, 0x1a, 0x58, 0xc9,
	0xa8, 0x0d, 0xe5, 0x84, 0x07, 0x9d, 0xb2, 0x32, 0x49, 0x51, 0x7a, 0x25, 0x31, 0xe5, 0x9d, 0x8a,
	0xf6, 0x92, 0x32, 0xb2, 0x61, 0xc3, 0x23, 0x82, 0x8c, 0x49, 0x4c, 0x3b, 0x55, 0x65, 0xcf, 0x74,
	0xf4, 0x31, 0xb4, 0xc7, 0x24, 0xf6, 0xdd, 0x47, 0x89, 0x98, 0x0d, 0x23, 0x32, 0x0e, 0xa8, 0xd7,
	0xa9, 0x75, 0xad, 0xad, 0x0d, 0xfc, 0x8a, 0x1d, 0xdd, 0x95, 0xf0, 0x8c, 0xed, 0x54, 0x3e, 0x52,
	0x57, 0xc9, 0x96, 0x8d, 0xbd, 0x5f, 0xca, 0xd0, 0x3a, 0x52, 0xb0, 0x0d, 0x90, 0xeb, 0x50, 0x65,
	0x7c, 0xfa, 0x34, 0xc5, 0xa2, 0x15, 0x59, 0x94, 0x6e, 0xce, 0x53, 0xcf, 0x40, 0xca, 0x74, 0x74,
	0x1b, 0x40, 0xcb, 0x27, 0x8b, 0x39, 0x35, 0xe8, 0x0a, 0x16, 0x19, 0xfb, 0x7d, 0xcc, 0x22, 0xd9,
	0x32, 0x05, 0xb4, 0x85, 0x33, 0x1d, 0x85, 0xf0, 0xbe, 0x47, 0x5d, 0xbe, 0x98, 0x0b, 0xea, 0x8d,
	0xa8, 0x9b, 0x70, 0xfa, 0x2c, 0x75, 0xad, 0x76, 0xcb, 0x5b, 0xcd, 0xfe, 0x03, 0x27, 0x1d, 0x8a,
	0x53, 0x2c, 0xd3, 0xd9, 0xb9, 0x3c, 0x6a, 0x18, 0x09, 0xbe, 0xc0, 0xab, 0x72, 0xa2, 0x5b, 0xd0,
	0x48, 0xe6, 0x1e, 0x11, 0xd4, 0xdb, 0x1f, 0xa9, 0xc6, 0x95, 0x71, 0x6e, 0x40, 0xbb, 0xd0, 0x96,
	0x9d, 0x8e, 0x0b, 0x73, 0x55, 0x4d, 0x6b, 0xf6, 0xed, 0xbc, 0x8a, 0x8b, 0x93, 0xc7, 0xaf, 0xc4,
	0xd8, 0xcf, 0xe0, 0xd6, 0xba, 0xf2, 0x24, 0x0f, 0xce, 0xe8, 0x42, 0x35, 0xb8, 0x81, 0xa5, 0x28,
	0x9b, 0x7e, 0x4e, 0x82, 0x24, 0xa5, 0x8b, 0x56, 0xb6, 0x4b, 0x5f, 0x59, 0xbd, 0x17, 0x50, 0x91,
	0x73, 0x92, 0x1e, 0x01, 0x9b, 0xfa, 0x91, 0x89, 0xd2, 0xca, 0xa5, 0x2c, 0xbb, 0x0e, 0x55, 0x1a,
	0x12, 0x3f, 0xe5, 0x99, 0x56, 0xa4, 0x27, 0x67, 0x01, 0x4d, 0x99, 0x26, 0xe5, 0xde, 0x1e, 0x34,
	0x4e, 0xfc, 0x90, 0x62, 0x12, 0x4d, 0x29, 0xea, 0x42, 0x73, 0xc2, 0x59, 0x38, 0x9c, 0x33, 0x77,
	0xb6, 0x3f, 0x32, 0xd3, 0x2f, 0x9a, 0x64, 0xf3, 0x04, 0x4b, 0x7f, 0x2f, 0xe9, 0xe6, 0x65, 0x86,
	0xde, 0x6f, 0x16, 0x34, 0x24, 0xc4, 0xe3, 0x84, 0x72, 0x05, 0x88, 0xd3, 0x89, 0x61, 0x51, 0x03,
	0x6b, 0x45, 0x52, 0x32, 0x24, 0x3f, 0x48, 0xaf, 0x23, 0xe6, 0x47, 0x22, 0x36, 0x59, 0x96, 0x8d,
	0x92, 0x4f, 0x7e, 0x24, 0x28, 0x3f, 0x27, 0xc1, 0xfe, 0x48, 0xa1, 0x28, 0xe3, 0x82, 0x05, 0x7d,
	0x01, 0x0d, 0x91, 0x96, 0xad, 0xf0, 0x34, 0xfb, 0xd7, 0xf2, 0xf9, 0x64, 0x88, 0x70, 0xee, 0x25,
	0xd1, 0x4b, 0xca, 0xa9, 0x7d, 0x6a, 0x61, 0x25, 0xf7, 0x7e, 0x2e, 0xe9, 0x35, 0x56, 0x05, 0x63,
	0xfa, 0x32, 0xa1, 0xb1, 0x40, 0x0e, 0xd4, 0x5c, 0x3d, 0x78, 0x4b, 0x25, 0xbe, 0x71, 0x39, 0xfd,
	0xb0, 0xf1, 0x42, 0x8f, 0xa0, 0x3e, 0xa3, 0xc4, 0xa3, 0x5c, 0x62, 0x91, 0x7c, 0xfd, 0x68, 0x99,
	0x29, 0xc5, 0xe4, 0xce, 0x13, 0xed, 0xa9, 0x39, 0x9a, 0xc6, 0xa1, 0xcf, 0xa0, 0xfe, 0x32, 0xa1,
	0xdc, 0xa7, 0x71, 0xa7, 0xac, 0x52, 0x5c, 0xbb, 0x2c, 0x45, 0xea, 0x83, 0x7a, 0x85, 0x93, 0xd1,
	0xec, 0x6f, 0xe6, 0xbe, 0x92, 0x26, 0xfa, 0x84, 0xd8, 0xdb, 0xd0, 0x2a, 0xbe, 0xf5, 0x46, 0x84,
	0xfb, 0xdd, 0x82, 0xab, 0x85, 0xca, 0xe3, 0x39, 0x8b, 0x62, 0x8a, 0x6e, 0x40, 0x6d, 0xc2, 0x49,
	0x48, 0xe3, 0x8e, 0xd5, 0x2d, 0x6f, 0xb5, 0xb0, 0xd1, 0xd0, 0x10, 0x36, 0x42, 0x2a, 0x88, 0x5c,
	0x01, 0xd3, 0x80, 0x7b, 0x97, 0x36, 0x40, 0xa7, 0x71, 0xf6, 0x8d, 0xaf, 0x6e, 0x41, 0x16, 0x6a,
	0x3f, 0x84, 0x2b, 0x4b, 0x3f, 0xbd, 0x51, 0xc5, 0xff, 0x56, 0xa0, 0x35, 0x20, 0x41, 0x80, 0xa9,
	0xde, 0x42, 0xfb, 0x2e, 0xc0, 0x48, 0x70, 0x3f, 0x9a, 0x3e, 0xf7, 0x63, 0x21, 0x4b, 0x57, 0xbe,
	0xba, 0xf4, 0x06, 0x36, 0x9a, 0xfd, 0x77, 0x09, 0xea, 0x6f, 0x3b, 0x76, 0x04, 0x95, 0x39, 0x11,
	0xb3, 0x74, 0xef, 0xa4, 0x2c, 0xdf, 0x09, 0xa9, 0x98, 0x31, 0xcf, 0x2c, 0x9e, 0xd1, 0xd2, 0xab,
	0x5f, 0xc9, 0xaf, 0xfe, 0x30, 0x27, 0x8d, 0x3e, 0x72, 0x9f, 0xe4, 0xcf, 0x15, 0x81, 0x38, 0xeb,
	0x89, 0x83, 0xa0, 0x32, 0x66, 0xde, 0x42, 0xdd, 0xb1, 0x16, 0x56, 0x72, 0xc6, 0x8e, 0xfa, 0x1a,
	0x76, 0x7c, 0xf7, 0x5a, 0x76, 0x7c, 0x59, 0xec, 0x75, 0xb3, 0x7f, 0x67, 0x45, 0x79, 0x79, 0x93,
	0x0b, 0xe3, 0xb0, 0xff, 0xb1, 0x60, 0x23, 0xe3, 0x0d, 0x82, 0x8a, 0xcb, 0x3c, 0xaa, 0x92, 0x57,
	0xb1, 0x92, 0xd1, 0xee, 0xc5, 0x9d, 0xf9, 0x74, 0x25, 0x7c, 0x43, 0x9b, 0xf5, 0xf8, 0xcb, 0x39,
	0xfe, 0xff, 0x19, 0x5b, 0xef, 0x27, 0x0b, 0x36, 0x07, 0x2c, 0x08, 0xa8, 0x2b, 0xf6, 0xa9, 0xe0,
	0xbe, 0x1b, 0xdb, 0x8d, 0x8c, 0x45, 0xf6, 0x3d, 0xa8, 0x1f, 0x91, 0x45, 0xc0, 0x88, 0xfe, 0x26,
	0x72, 0x26, 0x19, 0x40, 0x93, 0x58, 0x3d, 0xdf, 0xc2, 0x05, 0x8b, 0xbd, 0x5b, 0xe8, 0xd1, 0x36,
	0xd4, 0x43, 0x9d, 0xcc, 0xb0, 0xaf, 0x5b, 0xa8, 0x69, 0xe9, 0x31, 0xc7, 0xa4, 0xc7, 0x69, 0x40,
	0xef, 0xc7, 0x12, 0x34, 0x07, 0x33, 0xea, 0x9e, 0x3d, 0xa1, 0x24, 0x10, 0x33, 0xfb, 0xeb, 0xb7,
	0xe6, 0xb4, 0xfd, 0x67, 0x71, 0x6e, 0x03, 0xa8, 0xc5, 0x82, 0x08, 0x53, 0xfb, 0xe6, 0x12, 0x43,
	0xf3, 0xe7, 0x96, 0x26, 0x14, 0x88, 0xd9, 0x48, 0x85, 0x60, 0x13, 0x8a, 0x3a, 0x12, 0x58, 0x1c,
	0x93, 0x69, 0xba, 0xb4, 0xa9, 0x2a, 0x3f, 0x36, 0xea, 0x2f, 0x00, 0x15, 0xc4, 0x0f, 0x62, 0xb3,
	0x30, 0x45, 0x53, 0xcf, 0x51, 0x83, 0xcc, 0x72, 0xa2, 0x26, 0xd4, 0x4f, 0x0f, 0xf6, 0x0e, 0x0e,
	0xbf, 0x39, 0x68, 0xbf, 0x87, 0x6a, 0x50, 0x3a, 0xdc, 0x6b, 0x5b, 0xa8, 0x01, 0xd5, 0x21, 0xc6,
	0x87, 0xb8, 0x5d, 0xea, 0xff, 0x6a, 0x41, 0x65, 0xc0, 0x38, 0x45, 0xc7, 0xcb, 0xc7, 0x00, 0xdd,
	0x5e, 0xbf, 0x5b, 0xf6, 0x87, 0xaf, 0x21, 0xdf, 0xe7, 0x16, 0xda, 0x29, 0x7e, 0xd9, 0xec, 0xd5,
	0x07, 0xde, 0xbe, 0xb9, 0xe6, 0xf6, 0xf5, 0xff, 0xb0, 0xa0, 0xb9, 0xe3, 0x93, 0x69, 0xc4, 0x62,
	0xe1, 0xbb, 0x31, 0x3a, 0xbd, 0x48, 0x25, 0xb4, 0x7a, 0xee, 0xe9, 0x03, 0x77, 0xd6, 0x78, 0x98,
	0xc9, 0x3d, 0x5f, 0x22, 0x04, 0xfa, 0x60, 0xd5, 0xe0, 0x74, 0xc2, 0xdb, 0xeb, 0xe7, 0xda, 0x3f,
	0x86, 0xc6, 0x09, 0x27, 0x51, 0x3c, 0x61, 0x3c, 0x7c, 0x47, 0x7d, 0xf8, 0x16, 0xae, 0x66, 0x29,
	0x65, 0xc7, 0x1f, 0x13, 0xf7, 0xec, 0xdd, 0xa4, 0x7e, 0xdc, 0x7a, 0x01, 0xce, 0xc3, 0xf4, 0xf7,
	0x71, 0x4d, 0xfd, 0x5d, 0x7f, 0xf0, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x1d, 0x02, 0x7d,
	0xe6, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoreClient interface {
	// HTTP Style request
	CallResource(ctx context.Context, in *CallResource_Request, opts ...grpc.CallOption) (Core_CallResourceClient, error)
	// Well typed query interface
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
}

type coreClient struct {
	cc *grpc.ClientConn
}

func NewCoreClient(cc *grpc.ClientConn) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) CallResource(ctx context.Context, in *CallResource_Request, opts ...grpc.CallOption) (Core_CallResourceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Core_serviceDesc.Streams[0], "/pluginv2.Core/CallResource", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreCallResourceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_CallResourceClient interface {
	Recv() (*CallResource_Response, error)
	grpc.ClientStream
}

type coreCallResourceClient struct {
	grpc.ClientStream
}

func (x *coreCallResourceClient) Recv() (*CallResource_Response, error) {
	m := new(CallResource_Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, "/pluginv2.Core/DataQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
type CoreServer interface {
	// HTTP Style request
	CallResource(*CallResource_Request, Core_CallResourceServer) error
	// Well typed query interface
	DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
}

// UnimplementedCoreServer can be embedded to have forward compatible implementations.
type UnimplementedCoreServer struct {
}

func (*UnimplementedCoreServer) CallResource(req *CallResource_Request, srv Core_CallResourceServer) error {
	return status.Errorf(codes.Unimplemented, "method CallResource not implemented")
}
func (*UnimplementedCoreServer) DataQuery(ctx context.Context, req *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataQuery not implemented")
}

func RegisterCoreServer(s *grpc.Server, srv CoreServer) {
	s.RegisterService(&_Core_serviceDesc, srv)
}

func _Core_CallResource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallResource_Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).CallResource(m, &coreCallResourceServer{stream})
}

type Core_CallResourceServer interface {
	Send(*CallResource_Response) error
	grpc.ServerStream
}

type coreCallResourceServer struct {
	grpc.ServerStream
}

func (x *coreCallResourceServer) Send(m *CallResource_Response) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_DataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginv2.Core/DataQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DataQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Core_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginv2.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataQuery",
			Handler:    _Core_DataQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallResource",
			Handler:       _Core_CallResource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "backend.proto",
}

// DiagnosticsClient is the client API for Diagnostics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiagnosticsClient interface {
	CollectMetrics(ctx context.Context, in *CollectMetrics_Request, opts ...grpc.CallOption) (*CollectMetrics_Response, error)
	CheckHealth(ctx context.Context, in *CheckHealth_Request, opts ...grpc.CallOption) (*CheckHealth_Response, error)
}

type diagnosticsClient struct {
	cc *grpc.ClientConn
}

func NewDiagnosticsClient(cc *grpc.ClientConn) DiagnosticsClient {
	return &diagnosticsClient{cc}
}

func (c *diagnosticsClient) CollectMetrics(ctx context.Context, in *CollectMetrics_Request, opts ...grpc.CallOption) (*CollectMetrics_Response, error) {
	out := new(CollectMetrics_Response)
	err := c.cc.Invoke(ctx, "/pluginv2.Diagnostics/CollectMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagnosticsClient) CheckHealth(ctx context.Context, in *CheckHealth_Request, opts ...grpc.CallOption) (*CheckHealth_Response, error) {
	out := new(CheckHealth_Response)
	err := c.cc.Invoke(ctx, "/pluginv2.Diagnostics/CheckHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagnosticsServer is the server API for Diagnostics service.
type DiagnosticsServer interface {
	CollectMetrics(context.Context, *CollectMetrics_Request) (*CollectMetrics_Response, error)
	CheckHealth(context.Context, *CheckHealth_Request) (*CheckHealth_Response, error)
}

// UnimplementedDiagnosticsServer can be embedded to have forward compatible implementations.
type UnimplementedDiagnosticsServer struct {
}

func (*UnimplementedDiagnosticsServer) CollectMetrics(ctx context.Context, req *CollectMetrics_Request) (*CollectMetrics_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectMetrics not implemented")
}
func (*UnimplementedDiagnosticsServer) CheckHealth(ctx context.Context, req *CheckHealth_Request) (*CheckHealth_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckHealth not implemented")
}

func RegisterDiagnosticsServer(s *grpc.Server, srv DiagnosticsServer) {
	s.RegisterService(&_Diagnostics_serviceDesc, srv)
}

func _Diagnostics_CollectMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectMetrics_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServer).CollectMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginv2.Diagnostics/CollectMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServer).CollectMetrics(ctx, req.(*CollectMetrics_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Diagnostics_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealth_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagnosticsServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginv2.Diagnostics/CheckHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagnosticsServer).CheckHealth(ctx, req.(*CheckHealth_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Diagnostics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginv2.Diagnostics",
	HandlerType: (*DiagnosticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CollectMetrics",
			Handler:    _Diagnostics_CollectMetrics_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _Diagnostics_CheckHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

// TransformClient is the client API for Transform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransformClient interface {
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
}

type transformClient struct {
	cc *grpc.ClientConn
}

func NewTransformClient(cc *grpc.ClientConn) TransformClient {
	return &transformClient{cc}
}

func (c *transformClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, "/pluginv2.Transform/DataQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransformServer is the server API for Transform service.
type TransformServer interface {
	DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
}

// UnimplementedTransformServer can be embedded to have forward compatible implementations.
type UnimplementedTransformServer struct {
}

func (*UnimplementedTransformServer) DataQuery(ctx context.Context, req *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataQuery not implemented")
}

func RegisterTransformServer(s *grpc.Server, srv TransformServer) {
	s.RegisterService(&_Transform_serviceDesc, srv)
}

func _Transform_DataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServer).DataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginv2.Transform/DataQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServer).DataQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transform_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginv2.Transform",
	HandlerType: (*TransformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataQuery",
			Handler:    _Transform_DataQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

// TransformCallBackClient is the client API for TransformCallBack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransformCallBackClient interface {
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error)
}

type transformCallBackClient struct {
	cc *grpc.ClientConn
}

func NewTransformCallBackClient(cc *grpc.ClientConn) TransformCallBackClient {
	return &transformCallBackClient{cc}
}

func (c *transformCallBackClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (*DataQueryResponse, error) {
	out := new(DataQueryResponse)
	err := c.cc.Invoke(ctx, "/pluginv2.TransformCallBack/DataQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransformCallBackServer is the server API for TransformCallBack service.
type TransformCallBackServer interface {
	DataQuery(context.Context, *DataQueryRequest) (*DataQueryResponse, error)
}

// UnimplementedTransformCallBackServer can be embedded to have forward compatible implementations.
type UnimplementedTransformCallBackServer struct {
}

func (*UnimplementedTransformCallBackServer) DataQuery(ctx context.Context, req *DataQueryRequest) (*DataQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataQuery not implemented")
}

func RegisterTransformCallBackServer(s *grpc.Server, srv TransformCallBackServer) {
	s.RegisterService(&_TransformCallBack_serviceDesc, srv)
}

func _TransformCallBack_DataQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformCallBackServer).DataQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginv2.TransformCallBack/DataQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformCallBackServer).DataQuery(ctx, req.(*DataQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransformCallBack_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginv2.TransformCallBack",
	HandlerType: (*TransformCallBackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DataQuery",
			Handler:    _TransformCallBack_DataQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}
