name: Lint Go
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  GOLANGCI_LINT_VERSION: v1.61.0
jobs:
  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{env.GOLANGCI_LINT_VERSION}}
          args: |
            "./..." --timeout=7m
          skip-cache: true
          install-mode: binary
